---
title: "游닇 T칤tulo 01"
---

## T칤tulo I: De los derechos del titular de datos personales

### Art칤culo 4

**Art칤culo 4췈**.- Derechos del titular de datos. Toda persona, actuando por s칤 o a trav칠s de su representante legal o mandatario, seg칰n corresponda, tiene derecho de acceso, rectificaci칩n, supresi칩n, oposici칩n, portabilidad y bloqueo de sus datos personales, de conformidad con la presente ley.

Tales derechos son personales, intransferibles e irrenunciables, y no pueden limitarse por ning칰n acto o convenci칩n.  

En caso de fallecimiento del titular de datos, los derechos que reconoce esta ley pueden ser ejercidos por sus herederos. 

Con todo, los herederos no podr치n acceder a los datos del causante ni solicitar su rectificaci칩n o supresi칩n cuando la persona fallecida lo hubiese prohibido expresamente o as칤 lo establezca una ley.


### Art칤culo 5

**Art칤culo 5췈**.- Derecho de acceso. El titular de datos tiene derecho a solicitar y obtener del responsable confirmaci칩n acerca de si los datos personales que le conciernen est치n siendo tratados por 칠l y, en tal caso, acceder a dichos datos y a la siguiente informaci칩n:

**a)** Los datos tratados y su origen.

**b)** La finalidad o finalidades del tratamiento.

**c)** Las categor칤as, clases o tipos de destinatarios, o bien la identidad de cada destinatario en caso de solicitarlo as칤 el titular, a los que se les hayan comunicado o cedido los datos o se prevea hacerlo.

**d)** El per칤odo de tiempo durante el cual los datos ser치n tratados.

**e)** Los intereses leg칤timos del responsable cuando el tratamiento se base en lo dispuesto en el art칤culo 13 letra d).

**f)** Informaci칩n significativa sobre la l칩gica aplicada en el caso de que el responsable realice tratamiento de datos de conformidad con el art칤culo 8춿 bis.

El responsable siempre estar치 obligado a entregar informaci칩n y a dar acceso a los datos solicitados, excepto cuando una ley disponga expresamente lo contrario.


### Art칤culo 6

**Art칤culo 6췈**.- Derecho de rectificaci칩n. El titular de datos tiene derecho a solicitar y obtener del responsable la rectificaci칩n de los datos personales que le conciernen y que est치n siendo tratados por 칠l cuando sean inexactos, desactualizados o incompletos.

Los datos rectificados deber치n ser comunicados a las personas, entidades u organismos a los cuales el responsable haya comunicado o cedido los referidos datos, salvo en los casos en que dicha comunicaci칩n sea imposible o exija un esfuerzo desproporcionado.

Efectuada la rectificaci칩n, no se podr치n volver a tratar los datos sin rectificar.

### Art칤culo 7

**Art칤culo 7췈**.- Derecho de supresi칩n. El titular de datos tiene derecho a solicitar y obtener del responsable la eliminaci칩n de los datos personales que le conciernen en los siguientes casos:

**a)** Cuando los datos no resulten necesarios en relaci칩n con los fines del tratamiento para el cual fueron recogidos.

**b)** Cuando el titular haya revocado su consentimiento para el tratamiento y 칠ste no tenga otro fundamento legal. 

**c)** Cuando los datos hayan sido obtenidos o tratados il칤citamente por el responsable.

**d)** Cuando se trate de datos caducos.

**e)** Cuando los datos deban suprimirse para el cumplimiento de una sentencia judicial, de una resoluci칩n de la autoridad de protecci칩n de datos o de una obligaci칩n legal.

**f)** Cuando el titular haya ejercido su derecho de oposici칩n de conformidad al art칤culo siguiente y no exista otro fundamento legal para su tratamiento.

No procede la supresi칩n cuando el tratamiento sea necesario:

**i.** Para ejercer el derecho a las libertades de emitir opini칩n y de informar.

**ii.** Para el cumplimiento de una obligaci칩n legal o la ejecuci칩n de un contrato suscrito entre el titular y el responsable.

**iii.** Para el cumplimiento de una funci칩n p칰blica o para el ejercicio de una actividad de inter칠s p칰blico.

**iv.** Por razones de inter칠s p칰blico en el 치rea de la salud p칰blica, de conformidad con las condiciones y garant칤as establecidas en la ley.

**v.** Para tratamientos con fines hist칩ricos, estad칤sticos o cient칤ficos, y para estudios o investigaciones que atiendan fines de inter칠s p칰blico.

**vi.** Para la formulaci칩n, ejercicio o defensa de una reclamaci칩n administrativa o judicial.



### Art칤culo 8

**Art칤culo 8췈**.- Derecho de oposici칩n. El titular de datos tiene derecho a oponerse ante el responsable a que se realice un tratamiento espec칤fico o determinado de los datos personales que le conciernan en los siguientes casos:

**a)** Cuando la base de licitud del tratamiento sea la satisfacci칩n de intereses leg칤timos del responsable. En dicho caso, podr치 ejercer su derecho de oposici칩n en cualquier momento. El responsable del tratamiento deber치 dejar de tratar los datos personales, salvo que acredite motivos leg칤timos imperiosos para el tratamiento que prevalezcan sobre los intereses, los derechos y las libertades del titular, o para la formulaci칩n, el ejercicio o la defensa de reclamaciones.

**b)** Si el tratamiento se realiza exclusivamente con fines de mercadotecnia o marketing directo de bienes, productos o servicios, incluida la elaboraci칩n de perfiles de conformidad con el art칤culo 8춿 bis.

**c)** Si el tratamiento se realiza respecto de datos obtenidos de una fuente de acceso p칰blico y no existe otro fundamento legal para su tratamiento.

No proceder치 la oposici칩n al tratamiento cuando 칠ste se realice con fines de investigaci칩n cient칤fica o hist칩rica, o fines estad칤sticos, y siempre que fueran necesarios para el cumplimiento de una funci칩n p칰blica o para el ejercicio de una actividad de inter칠s p칰blico.


**Art칤culo 8췈 bis**.- Decisiones individuales automatizadas, incluida la elaboraci칩n de perfiles. El titular de datos tiene derecho a oponerse y a no ser objeto de decisiones basadas en el tratamiento automatizado de sus datos personales, incluida la elaboraci칩n de perfiles, que produzca efectos jur칤dicos en 칠l o le afecte significativamente.

El inciso anterior no se aplicar치 en los siguientes casos:

**a)** Cuando la decisi칩n sea necesaria para la celebraci칩n o ejecuci칩n de un contrato entre el titular y el responsable.

**b)** Cuando exista consentimiento previo y expreso del titular en la forma prescrita en el art칤culo 12.

**c)** Cuando lo se침ale la ley, en la medida en que 칠sta disponga el empleo de salvaguardas a los derechos y libertades del titular.

En todos los casos de decisiones basadas en el tratamiento automatizado de datos personales, inclusive aquellos se침alados en las letras **a)**, **b)** y **c)** precedentes, el responsable deber치 adoptar las medidas necesarias para asegurar los derechos y libertades del titular, su derecho a la informaci칩n y transparencia, el derecho a obtener una explicaci칩n, la intervenci칩n humana, a expresar su punto de vista y a solicitar la revisi칩n de la decisi칩n.

**Art칤culo 8췈 ter**.- Derecho de bloqueo del tratamiento. El titular de datos tiene derecho a solicitar la suspensi칩n temporal de cualquier operaci칩n de tratamiento de sus datos personales cuando formule una solicitud de rectificaci칩n, supresi칩n u oposici칩n de conformidad con el art칤culo 11 de la presente ley, mientras dicha solicitud no se resuelva.

Asimismo, el titular podr치 ejercer este derecho alternativamente al de supresi칩n en los casos del art칤culo 7췈.

El ejercicio de este derecho no afectar치 el almacenamiento de los datos por parte del responsable.

### Art칤culo 9

**Art칤culo 9췈**.- Derecho a la portabilidad de los datos personales. El titular de datos tiene derecho a solicitar y recibir una copia de los datos personales que le conciernen y que haya facilitado al responsable en un formato electr칩nico, estructurado, gen칠rico y de uso com칰n, que permita ser operado por distintos sistemas y a comunicarlos o transferirlos a otro responsable de datos cuando concurran las siguientes circunstancias:

**a)** El tratamiento se realice en forma automatizada y

**b)** El tratamiento est칠 basado en el consentimiento del titular.

El responsable debe utilizar los medios m치s expeditos, menos onerosos y sin poner trabas u obst치culos para el ejercicio de este derecho.

El responsable tambi칠n debe comunicar al titular de manera clara y precisa las medidas necesarias para obtener sus datos personales y especificar las caracter칤sticas t칠cnicas para llevar a cabo estas operaciones.

El titular tendr치 derecho a que sus datos personales se transmitan directamente de responsable a responsable cuando sea t칠cnicamente posible.

Con todo, el ejercicio del derecho de portabilidad no supondr치 la supresi칩n de los datos ante el responsable cedente, a menos que el titular de ellos as칤 lo pida conjuntamente en la solicitud.


### Art칤culo 10

**Art칤culo 10췈**.- Forma y medios de ejercer los derechos del titular de datos. Los derechos reconocidos en esta ley se ejercen por el titular ante el responsable de datos. Si los datos personales del titular son tratados por diversos responsables, el titular puede ejercer sus derechos ante cualquiera de ellos. 

En el caso de las personas jur칤dicas no constituidas en Chile, el responsable deber치 se침alar por escrito ante la Agencia un correo electr칩nico o un medio de comunicaci칩n electr칩nico equivalente v치lido y operativo de una persona natural o jur칤dica capaz de actuar en su nombre para los efectos de que el titular pueda ejercer sus derechos y comunicarse con el responsable, y donde se le practiquen v치lidamente las comunicaciones y notificaciones administrativas que disponga la ley. El responsable deber치 mantener actualizada esta informaci칩n.

Los responsables de datos deber치n implementar mecanismos y herramientas tecnol칩gicas que permitan que el titular ejerza sus derechos de forma expedita, 치gil y eficaz. Los medios dispuestos por el responsable deben ser sencillos en su operaci칩n.

El ejercicio de los derechos de rectificaci칩n, supresi칩n y oposici칩n siempre ser치 gratuito para el titular. El derecho de acceso tambi칠n se ejercer치 en forma gratuita al menos trimestralmente.

El responsable de datos s칩lo puede exigir el pago de los costos directos en que incurra cuando el titular ejerza su derecho de acceso y derecho a la portabilidad m치s de una vez en el trimestre. El responsable no podr치 exigir este pago en los casos del inciso cuarto del art칤culo 28.

Los par치metros y mecanismos para determinar los costos derivados del ejercicio de los derechos se침alados en el inciso anterior ser치n determinados por la Agencia a trav칠s de una instrucci칩n general que considerar치, entre otros antecedentes, el volumen de los datos a ser entregados, la naturaleza jur칤dica y el tama침o de la entidad o empresa que tenga la calidad de responsable.

La Agencia velar치 por el efectivo ejercicio y cumplimiento de los derechos que esta ley reconoce al titular de datos, en conformidad con lo dispuesto en esta ley.


### Art칤culo 11

**Art칤culo 11췈**.- Procedimiento ante el responsable de datos. Para ejercer los derechos que le reconoce esta ley, el titular deber치 presentar una solicitud o requerimiento escrito ante el responsable, dirigido a la direcci칩n de correo electr칩nico establecida para este fin, un formulario de contacto o un medio electr칩nico equivalente. La solicitud deber치 contener al menos las siguientes menciones:

**a)** Individualizaci칩n del titular y de su representante legal o mandatario, seg칰n corresponda, y autenticaci칩n de su identidad de acuerdo con los procedimientos, formas y modalidades que establezca la Agencia.

**b)** Indicaci칩n de un domicilio o una direcci칩n de correo electr칩nico o de otro medio equivalente para comunicar la respuesta.

**c)** Identificaci칩n de los datos personales o del tratamiento determinado respecto de los cuales se ejerce el derecho correspondiente.

**d)** En las solicitudes de rectificaci칩n, el titular deber치 indicar las modificaciones o actualizaciones precisas a realizar y acompa침ar, en su caso, los antecedentes que las sustenten. Cuando se trate de solicitudes de supresi칩n, el titular deber치 indicar la causal invocada y acompa침ar los antecedentes que la sustenten, si correspondiere. Para las solicitudes de oposici칩n, el titular deber치 indicar la causal invocada y, en el caso de la letra **a)** del art칤culo 8췈, deber치 fundamentar brevemente su petici칩n y podr치 igualmente acompa침ar los antecedentes que estime procedentes. En el caso del derecho de acceso, bastar치 con la individualizaci칩n del titular.

Recibida la solicitud, el responsable deber치 acusar recibo de ella y pronunciarse a m치s tardar dentro de los treinta d칤as corridos siguientes a la fecha de ingreso de la solicitud. Este plazo podr치 ser prorrogado por una sola vez hasta por treinta d칤as corridos.

El responsable deber치 responder por escrito al titular a su domicilio o la direcci칩n de correo electr칩nico fijada por 칠ste. El responsable debe almacenar los respaldos que le permitan demostrar la remisi칩n de la respuesta a la direcci칩n f칤sica o electr칩nica que corresponda, su fecha y el contenido 칤ntegro de ella.

En caso de denegaci칩n total o parcial de la solicitud, el responsable deber치 fundar su decisi칩n indicando la causa invocada y los antecedentes que la justifican. En esta misma oportunidad, el responsable debe se침alar al titular que dispone de un plazo de treinta d칤as h치biles para formular una reclamaci칩n ante la Agencia de acuerdo con el procedimiento establecido en el art칤culo 41.

Transcurrido el plazo al que hace referencia el inciso segundo anterior sin que haya respuesta del responsable, el titular podr치 formular directamente una reclamaci칩n ante la Agencia en los mismos t칠rminos del inciso anterior.

Cuando se formule una solicitud de rectificaci칩n, supresi칩n u oposici칩n, el titular tendr치 derecho a solicitar y obtener del responsable el bloqueo temporal de sus datos o del tratamiento que realice, seg칰n corresponda. La solicitud de bloqueo temporal deber치 ser fundada y el responsable deber치 responder al requerimiento dentro de los dos d칤as h치biles siguientes a su recepci칩n. En tanto no resuelva esta solicitud, el responsable no podr치 tratar los datos del titular que forman parte del requerimiento. El bloqueo temporal de los datos no afectar치 su almacenamiento por parte del responsable. En caso de rechazo, el responsable deber치 fundar su respuesta y comunicar en forma electr칩nica su decisi칩n a la Agencia. El titular podr치 reclamar de esta decisi칩n ante la Agencia aplic치ndose lo dispuesto en la letra **a)** del inciso segundo del art칤culo 41.

La rectificaci칩n, supresi칩n u oposici칩n al tratamiento de los datos se aplicar치 s칩lo respecto de los responsables a quienes se les haya formulado la solicitud. Con todo, cuando el responsable haya comunicado dichos datos a otras personas, deber치 comunicar a 칠stas los cambios realizados en virtud de la rectificaci칩n, supresi칩n u oposici칩n.

El titular podr치 aportar cualquier otro antecedente que facilite la localizaci칩n de los datos personales.
