---
title: "游닇 T칤tulo 02"
---

## T칤tulo  II: Del tratamiento de los datos personales y de las categor칤as especiales de datos

### Art칤culo 12

**Art칤culo 12췈**.- Regla general del tratamiento de datos. Es l칤cito el tratamiento de los datos personales que le conciernen al titular cuando 칠ste otorgue su consentimiento para ello.

El consentimiento del titular debe ser libre, informado y espec칤fico en cuanto a su finalidad o finalidades. El consentimiento debe manifestarse adem치s en forma previa y de manera inequ칤voca mediante una declaraci칩n verbal, escrita o expresada a trav칠s de un medio electr칩nico equivalente o mediante un acto afirmativo que d칠 cuenta con claridad de la voluntad del titular.

Cuando el consentimiento lo otorgue un mandatario, 칠ste deber치 encontrarse expresamente premunido de esta facultad. 

El titular puede revocar el consentimiento otorgado en cualquier momento y sin expresi칩n de causa, utilizando medios similares o equivalentes a los empleados para su otorgamiento. La revocaci칩n del consentimiento no tendr치 efectos retroactivos.

Los medios utilizados para el otorgamiento o la revocaci칩n del consentimiento deben ser expeditos, fidedignos, gratuitos y estar permanentemente disponibles para el titular.

Se presume que el consentimiento para tratar datos no ha sido libremente otorgado cuando el responsable lo recaba en el marco de la ejecuci칩n de un contrato o la prestaci칩n de un servicio en que no es necesario efectuar esa recolecci칩n.

Con todo, lo dispuesto en el inciso anterior no se aplicar치 cuando quien ofrezca bienes, servicios o beneficios requiera como 칰nica contraprestaci칩n el consentimiento para tratar datos.

Corresponde al responsable probar que cont칩 con el consentimiento del titular y que el tratamiento de datos fue realizado en forma l칤cita, leal y transparente.



### Art칤culo 13

**Art칤culo 13췈**.- Otras fuentes de licitud del tratamiento de datos. Es l칤cito el tratamiento de datos personales sin el consentimiento del titular en los siguientes casos:

**a)** Cuando el tratamiento est칠 referido a datos relativos a obligaciones de car치cter econ칩mico, financiero, bancario o comercial y se realice de conformidad con las normas del T칤tulo III de esta ley, incluidos los datos referidos a la situaci칩n socioecon칩mica del titular.

**b)** Cuando el tratamiento sea necesario para la ejecuci칩n o el cumplimiento de una obligaci칩n legal o lo disponga la ley.

**c)** Cuando el tratamiento de datos sea necesario para la celebraci칩n o ejecuci칩n de un contrato entre el titular y el responsable, o para la ejecuci칩n de medidas precontractuales adoptadas a solicitud del titular.

**d)** Cuando el tratamiento sea necesario para la satisfacci칩n de intereses leg칤timos del responsable o de un tercero, siempre que con ello no se afecten los derechos y libertades del titular. En todo caso, el titular podr치 exigir siempre ser informado sobre el tratamiento que lo afecta y cu치l es el inter칠s leg칤timo en base al cual se efect칰a dicho tratamiento.

**e)** Cuando el tratamiento de datos sea necesario para la formulaci칩n, ejercicio o defensa de un derecho ante los tribunales de justicia u 칩rganos p칰blicos. 

El responsable deber치 acreditar la licitud del tratamiento de datos.



### Art칤culo 14

**Art칤culo 14췈**.- Obligaciones del responsable de datos. El responsable de datos, sin perjuicio de las dem치s disposiciones previstas en esta ley, tiene las siguientes obligaciones:

**a)** Informar y poner a disposici칩n del titular los antecedentes que acrediten la licitud del tratamiento de datos que realiza. Asimismo, deber치 entregar de manera expedita dicha informaci칩n cuando le sea requerida.

**b)** Asegurar que los datos personales se recojan de fuentes de acceso l칤citas, con fines espec칤ficos, expl칤citos y l칤citos, y que su tratamiento se limite al cumplimiento de estos fines.

**c)** Comunicar o ceder, en conformidad con las disposiciones de esta ley, informaci칩n exacta, completa y actual.

**d)** Suprimir o anonimizar los datos personales del titular cuando fueron obtenidos para la ejecuci칩n de medidas precontractuales.

**e)** Cumplir con los dem치s deberes, principios y obligaciones que rigen el tratamiento de los datos personales previstos en esta ley.

El responsable de datos que no tenga domicilio en Chile y que realice tratamiento de datos de personas que residan en el territorio nacional deber치 se침alar y mantener actualizado y operativo un correo electr칩nico u otro medio de contacto id칩neo para recibir comunicaciones de los titulares de datos y de la Agencia.


**Art칤culo 14췈 bis**.- Deber de secreto o confidencialidad. El responsable de datos est치 obligado a mantener secreto o confidencialidad acerca de los datos personales que conciernan a un titular, salvo cuando el titular los hubiere hecho manifiestamente p칰blicos. Este deber subsiste a칰n despu칠s de concluida la relaci칩n con el titular. En caso de que el responsable haya realizado alguna acci칩n sobre datos personales obtenidos de fuentes de acceso p칰blico, tales como organizarlos o clasificarlos bajo alg칰n criterio o combinarlos o complementarlos con otros datos, los datos personales que resulten de dicha acci칩n se encontrar치n protegidos bajo el presente deber de secreto o confidencialidad.

El deber de secreto o confidencialidad no obsta a las comunicaciones o cesiones de datos que deba realizar el responsable en conformidad a la ley y al cumplimiento de la obligaci칩n de dar acceso al titular e informar el origen de los datos cuando esta informaci칩n le sea requerida por el titular o por un 칩rgano p칰blico dentro del 치mbito de sus competencias legales.

El responsable debe adoptar las medidas necesarias con el objeto de que sus dependientes o las personas naturales o jur칤dicas que ejecuten operaciones de tratamiento de datos bajo su responsabilidad cumplan el deber de secreto o confidencialidad establecidos en este art칤culo. 


**Art칤culo 14췈 ter**.- Deber de informaci칩n y transparencia. El responsable de datos debe facilitar y mantener permanentemente a disposici칩n del p칰blico, en su sitio web o en cualquier otro medio de informaci칩n equivalente, al menos la siguiente informaci칩n:

**a)** La pol칤tica de tratamiento de datos personales que haya adoptado, la fecha y versi칩n de la misma.

**b)** La individualizaci칩n del responsable de datos y su representante legal, y la identificaci칩n del encargado de prevenci칩n, si existiere.

**c)** El domicilio postal, la direcci칩n de correo electr칩nico, el formulario de contacto o la identificaci칩n del medio tecnol칩gico equivalente de uso com칰n y f치cil acceso mediante el cual se le notifican las solicitudes que realicen los titulares.

**d)** Las categor칤as, clases o tipos de datos que trata; la descripci칩n gen칠rica del universo de personas que comprenden sus bases de datos; los destinatarios a los que se prev칠 comunicar o ceder los datos; las finalidades de los tratamientos que realiza; la base de legitimidad del tratamiento; y, en caso de tratamientos que se basan en la satisfacci칩n de intereses leg칤timos, cu치les ser칤an 칠stos.

**e)** La pol칤tica y las medidas de seguridad adoptadas para proteger las bases de datos personales que administra.

**f)** El derecho que le asiste al titular para solicitar ante el responsable acceso, rectificaci칩n, supresi칩n, oposici칩n y portabilidad de sus datos personales, de conformidad a la ley.

**g)** El derecho que le asiste al titular de recurrir ante la Agencia en caso de que el responsable rechace o no responda oportunamente las solicitudes que le formule.

**h)** En su caso, la transferencia de datos personales a un tercer pa칤s u organizaci칩n internacional, y si 칠stos ofrecen o no un nivel adecuado de protecci칩n. En caso de que no cuenten con un nivel adecuado de protecci칩n, se deber치 informar si existen garant칤as que justifiquen tal transferencia.

**i)** El periodo durante el que se conservar치n los datos personales.

**j)** La fuente de la cual provienen los datos personales y, en su caso, si proceden de fuentes de acceso p칰blico.

**k)** Cuando el tratamiento est치 basado en el consentimiento del titular, la existencia del derecho a retirarlo en cualquier momento sin que ello afecte a la licitud del tratamiento basado en el consentimiento previo a su retirada.

**l)** La existencia de decisiones automatizadas, incluida la elaboraci칩n de perfiles. En tales casos, informaci칩n significativa sobre la l칩gica aplicada, as칤 como las consecuencias previstas de dicho tratamiento para el titular.


**Art칤culo 14췈 qu치ter**.- Deber de protecci칩n desde el dise침o y por defecto. Con la finalidad de cumplir los principios y los derechos de los titulares establecidos en esta ley, el responsable debe aplicar medidas t칠cnicas y organizativas adecuadas desde el dise침o, con anterioridad y durante el tratamiento de los datos personales. Las medidas a aplicar deber치n tener en consideraci칩n el estado de la t칠cnica; los costos de implementaci칩n; la naturaleza, 치mbito, contexto y fines del tratamiento de datos; as칤 como los riesgos asociados a dicha actividad.

Asimismo, el responsable de datos deber치 aplicar medidas t칠cnicas y organizativas para garantizar que, por defecto, s칩lo sean objeto de tratamiento los datos personales espec칤ficos y estrictamente necesarios para dicha actividad. Para ello se tendr치 en consideraci칩n el n칰mero de datos recogidos, la extensi칩n del tratamiento, el plazo de conservaci칩n y su accesibilidad.



**Art칤culo 14췈 quinquies**.- Deber de adoptar medidas de seguridad. El responsable de datos debe adoptar las medidas necesarias para resguardar el cumplimiento del principio de seguridad establecido en esta ley, considerando el estado actual de la t칠cnica y los costos de aplicaci칩n, junto con la naturaleza, alcance, contexto y fines del tratamiento, as칤 como la probabilidad de los riesgos y la gravedad de sus efectos en relaci칩n con el tipo de datos tratados. Las medidas aplicadas por el responsable deben asegurar la confidencialidad, integridad, disponibilidad y resiliencia de los sistemas de tratamiento de datos. Asimismo, deber치n evitar la alteraci칩n, destrucci칩n, p칠rdida, tratamiento o acceso no autorizado.

En consideraci칩n al estado de la t칠cnica, los costos de aplicaci칩n y la naturaleza, el alcance, el contexto y los fines del tratamiento, as칤 como los riesgos de probabilidad y gravedad variables para los derechos y libertades de los titulares, el responsable y el encargado del tratamiento aplicar치n medidas t칠cnicas y organizativas apropiadas para garantizar un nivel de seguridad adecuado al riesgo que, en su caso, incluya entre otros:

**a)** La seudonimizaci칩n y el cifrado de datos personales.

**b)** La capacidad de garantizar la confidencialidad, integridad, disponibilidad y resiliencia permanentes de los sistemas y servicios de tratamiento.

**c)** La capacidad de restaurar la disponibilidad y el acceso a los datos personales de forma r치pida en caso de incidente f칤sico o t칠cnico.

**d)** Un proceso de verificaci칩n, evaluaci칩n y valoraci칩n regulares de la eficacia de las medidas t칠cnicas y organizativas para garantizar la seguridad del tratamiento.


**Art칤culo 14췈 sexies**.- Deber de reportar las vulneraciones a las medidas de seguridad. El responsable deber치 reportar a la Agencia por los medios m치s expeditos posibles y sin dilaciones indebidas las vulneraciones a las medidas de seguridad que ocasionen la destrucci칩n, filtraci칩n, p칠rdida o alteraci칩n accidental o il칤cita de los datos personales que trate, o la comunicaci칩n o acceso no autorizados a dichos datos, cuando exista un riesgo razonable para los derechos y libertades de los titulares.

El responsable deber치 registrar estas comunicaciones, describiendo la naturaleza de las vulneraciones sufridas, sus efectos, las categor칤as de datos y el n칰mero aproximado de titulares afectados, y las medidas adoptadas para gestionarlas y precaver incidentes futuros.

Cuando dichas vulneraciones se refieran a datos personales sensibles, datos relativos a ni침os y ni침as menores de catorce a침os, o datos relativos a obligaciones de car치cter econ칩mico, financiero, bancario o comercial, el responsable deber치 tambi칠n efectuar esta comunicaci칩n a los titulares de estos datos a trav칠s de sus representantes, cuando corresponda. Esta comunicaci칩n deber치 realizarse en un lenguaje claro y sencillo, singularizando los datos afectados, las posibles consecuencias de las vulneraciones de seguridad y las medidas de soluci칩n o resguardo adoptadas. La notificaci칩n se deber치 realizar a cada titular afectado y, si ello no fuere posible, se realizar치 mediante la difusi칩n o publicaci칩n de un aviso en un medio de comunicaci칩n social masivo y de alcance nacional.

Los deberes de informaci칩n se침alados en este art칤culo no obstan a los dem치s deberes de informaci칩n que establezcan otras leyes.


**Art칤culo 14췈 septies**.- Diferenciaci칩n de est치ndares de cumplimiento. Los est치ndares o condiciones m칤nimas que se impongan al responsable de datos para el cumplimiento de los deberes de informaci칩n y de seguridad establecidos en los art칤culos 14 ter y 14 quinquies, respectivamente, ser치n determinados considerando el tipo de dato del que se trata, si el responsable es una persona natural o jur칤dica, el tama침o de la entidad o empresa de acuerdo a las categor칤as establecidas en el art칤culo segundo de la ley N춿 20.416 que fija normas especiales para las empresas de menor tama침o, la actividad que desarrolla y el volumen, naturaleza y las finalidades de los datos personales que trata.

Los est치ndares o condiciones m칤nimas de cumplimiento y las medidas diferenciadas a que alude el inciso anterior ser치n determinados por la Agencia mediante instrucci칩n general.



### Art칤culo 15

**Art칤culo 15췈**.- Cesi칩n de datos personales. Los datos personales podr치n ser cedidos con el consentimiento del titular y para el cumplimiento de los fines del tratamiento. Tambi칠n se podr치n ceder los datos personales cuando la cesi칩n sea necesaria para el cumplimiento y la ejecuci칩n de un contrato en que es parte el titular; cuando exista un inter칠s leg칤timo del cedente o del cesionario en los t칠rminos previstos en la letra **d)** del art칤culo 13, y cuando lo disponga la ley. 

En caso de que el consentimiento otorgado por el titular al momento de realizarse la recolecci칩n de los datos personales no haya considerado la cesi칩n de los mismos, 칠ste debe recabarse antes que se produzca, consider치ndose para todos los efectos legales como una nueva operaci칩n de tratamiento.

La cesi칩n de datos deber치 constar por escrito o a trav칠s de cualquier medio electr칩nico id칩neo. En ella se deber치 individualizar a las partes, los datos que son objeto de la cesi칩n, las finalidades previstas para el tratamiento y los dem치s antecedentes o estipulaciones que acuerden el cedente y el cesionario.

El tratamiento de los datos personales cedidos deber치 realizarse por el cesionario de conformidad a las finalidades establecidas en el contrato de cesi칩n. 

Una vez perfeccionada la cesi칩n, el cesionario adquiere la condici칩n de responsable de datos para todos los efectos legales. El cedente, por su parte, tambi칠n mantiene la calidad de responsable de datos respecto de las operaciones de tratamiento que contin칰e realizando.

Si se verifica una cesi칩n de datos sin contar con el consentimiento del titular, siendo 칠ste necesario, la cesi칩n ser치 nula, debiendo el cesionario suprimir todos los datos recibidos sin perjuicio de las responsabilidades legales que correspondan.

**Art칤culo 15췈 bis**.- Tratamiento de datos a trav칠s de un tercero mandatario o encargado. El responsable puede efectuar el tratamiento de datos en forma directa o a trav칠s de un tercero mandatario o encargado. En este 칰ltimo caso, el tercero mandatario o encargado realiza el tratamiento de datos personales conforme al encargo y a las instrucciones que le imparta el responsable, qued치ndole prohibido su tratamiento para un objeto distinto del convenido con el responsable, as칤 como su cesi칩n o entrega en los casos en que el responsable no lo haya autorizado de manera expresa y espec칤ficamente para cumplir con el objeto del encargo. 

Si el tercero mandatario o encargado trata los datos con un objeto distinto del encargo convenido o los cede o entrega sin haber sido autorizado en los t칠rminos dispuestos en el inciso anterior, se le considerar치 como responsable de datos para todos los efectos legales, debiendo responder personalmente por las infracciones en que incurra y solidariamente con el responsable de datos por los da침os ocasionados, sin perjuicio de las responsabilidades contractuales que le correspondan frente al mandante o responsable de datos.

El tratamiento de datos a trav칠s de un tercero mandatario o encargado se regir치 por el contrato celebrado entre el responsable y el encargado, con arreglo a la legislaci칩n vigente. En el contrato se deber치 establecer el objeto del encargo, la duraci칩n del mismo, la finalidad del tratamiento, el tipo de datos personales tratados, las categor칤as de titulares a quienes conciernen los datos y los derechos y obligaciones de las partes. El encargado no podr치 delegar parte o la totalidad del encargo salvo que conste una autorizaci칩n espec칤fica y por escrito del responsable. El encargado que delegue a otro encargado parte o la totalidad del encargo continuar치 siendo solidariamente responsable sobre dicho encargo y no podr치 eximirse de responsabilidad argumentando que ha delegado el tratamiento. La Agencia pondr치 a disposici칩n del p칰blico modelos tipo de contratos en su p치gina web.

El tercero mandatario o encargado deber치 cumplir con lo dispuesto en los art칤culos 14 bis y 14 quinquies. La diferenciaci칩n de est치ndares de cumplimiento establecida en el inciso primero del art칤culo 14 septies tambi칠n ser치 aplicable al tercero mandatario o encargado. Trat치ndose de una vulneraci칩n a las medidas de seguridad, el tercero o mandatario deber치 reportar este hecho al responsable.

Cumplida la prestaci칩n del servicio de tratamiento por parte del tercero mandatario o encargado, los datos que obren en su poder deben ser suprimidos o devueltos al responsable de datos, seg칰n corresponda. 


**Art칤culo 15췈 ter**.- Evaluaci칩n de impacto en protecci칩n de datos personales. Cuando sea probable que un tipo de tratamiento, por su naturaleza, alcance, contexto, tecnolog칤a utilizada o fines, pueda producir un alto riesgo para los derechos de las personas titulares de los datos personales, el responsable del tratamiento deber치 realizar, previo al inicio de las operaciones del tratamiento, una evaluaci칩n del impacto en protecci칩n de datos personales.

La evaluaci칩n de impacto se requerir치 siempre en casos de:

**a)** Evaluaci칩n sistem치tica y exhaustiva de aspectos personales de los titulares de datos basadas en tratamiento o decisiones automatizadas, como la elaboraci칩n de perfiles, y que produzcan en ellos efectos jur칤dicos significativos.

**b)** Tratamiento masivo de datos o a gran escala.

**c)** Tratamiento que implique observaci칩n o monitoreo sistem치tico de una zona de acceso p칰blico.

**d)** Tratamiento de datos sensibles y especialmente protegidos en las hip칩tesis de excepci칩n del consentimiento.

La Agencia de Protecci칩n de Datos establecer치 y publicar치 una lista orientativa de los tipos de operaciones de tratamiento que requieran o no una evaluaci칩n de impacto relativa a la protecci칩n de datos personales. La Agencia tambi칠n establecer치 las orientaciones m칤nimas para realizar esta evaluaci칩n, considerando a lo menos en dichos criterios la descripci칩n de las operaciones de tratamiento, su finalidad, la evaluaci칩n de la necesidad y la proporcionalidad con respecto a su finalidad, la evaluaci칩n de los riesgos y medidas de mitigaci칩n.

Los responsables podr치n consultar a la Agencia de Protecci칩n de Datos cuando, en virtud del resultado de la evaluaci칩n, el tratamiento demuestre ser de alto riesgo a efectos de obtener recomendaciones de parte de dicha entidad.




### Art칤culo 16

**Art칤culo 16췈**.- Regla general para el tratamiento de datos personales sensibles. El tratamiento de los datos personales sensibles s칩lo puede realizarse cuando el titular a quien conciernen estos datos manifiesta su consentimiento en forma expresa, otorgado a trav칠s de una declaraci칩n escrita, verbal o por un medio tecnol칩gico equivalente.

Sin perjuicio de lo anterior, es l칤cito el tratamiento de datos personales sensibles, sin el consentimiento del titular, en los siguientes casos:

**a)** Cuando el tratamiento se refiere a datos personales sensibles que el titular ha hecho manifiestamente p칰blicos y su tratamiento est칠 relacionado con los fines para los cuales fueron publicados.

**b)** Cuando el tratamiento se basa en un inter칠s leg칤timo realizado por una persona jur칤dica de derecho p칰blico o de derecho privado que no persiga fines de lucro y se cumplan las siguientes condiciones: 

**i.** Su finalidad sea pol칤tica, filos칩fica, religiosa, cultural, sindical o gremial;

**ii.** El tratamiento que realice se refiera exclusivamente a sus miembros o afiliados; 

**iii.** El tratamiento de datos tenga por objeto cumplir las finalidades espec칤ficas de la instituci칩n;

**iv.** La persona jur칤dica otorgue las garant칤as necesarias para evitar filtraciones, sustracciones o un uso o tratamiento no autorizado de los datos, y 

**v.** Los datos personales no se comuniquen o cedan a terceros.

Cumpli칠ndose estas condiciones, la persona jur칤dica no requerir치 el consentimiento del titular para tratar sus datos, incluidos los datos personales sensibles. En caso de duda o controversia administrativa o judicial, el responsable de datos deber치 acreditar su concurrencia.

Cuando un integrante de la persona jur칤dica deje de pertenecer a ella, sus datos deber치n ser anonimizados o suprimidos.

**c)** Cuando el tratamiento de los datos personales del titular resulte indispensable para salvaguardar la vida, salud o integridad f칤sica o ps칤quica del titular o de otra persona o, cuando el titular se encuentre f칤sica o jur칤dicamente impedido de otorgar su consentimiento. Una vez que cese el impedimento, el responsable debe informar detalladamente al titular los datos que fueron tratados y las operaciones espec칤ficas de tratamiento que fueron realizadas.

**d)** Cuando el tratamiento de los datos sea necesario para la formulaci칩n, ejercicio o defensa de un derecho ante los tribunales de justicia o un 칩rgano administrativo.

**e)** Cuando el tratamiento de datos sea necesario para el ejercicio de derechos y el cumplimiento de obligaciones del responsable o del titular de datos, en el 치mbito laboral o de seguridad social, y se realice en el marco de la ley.

**f)** Cuando el tratamiento de datos personales sensibles lo autorice o mandate expresamente la ley.

Las excepciones para tratar datos sin consentimiento, mencionadas en este art칤culo, se entienden aplicables al tratamiento de datos que no revisten el car치cter de datos sensibles.



**Art칤culo 16췈 bis**.- Datos personales sensibles relativos a la salud y al perfil biol칩gico humano. Si se cumple lo dispuesto en el inciso primero del art칤culo 16, los datos personales relativos a la salud del titular, as칤 como aquellos relativos al perfil biol칩gico del titular, tales como los datos gen칠ticos, prote칩micos o metab칩licos, s칩lo podr치n ser tratados para los fines previstos por las leyes especiales en materia sanitaria.

S칩lo se podr치n tratar los datos personales sensibles relativos a la salud del titular y a su perfil biol칩gico, sin contar con su consentimiento, respetando los principios y reglas establecidos en la presente ley, en los siguientes casos:

**a)** Cuando 칠ste resulte indispensable para salvaguardar la vida o integridad f칤sica o ps칤quica del titular o de otra persona o, cuando el titular se encuentre f칤sica o jur칤dicamente impedido de otorgar su consentimiento. Una vez que cese el impedimento, el responsable debe informar detalladamente al titular los datos que fueron tratados y las operaciones espec칤ficas de tratamiento que fueron realizadas.

**b)** En casos de alerta sanitaria legalmente decretada.

**c)** Cuando sean utilizados con fines hist칩ricos, estad칤sticos o cient칤ficos, para estudios o investigaciones que atiendan fines de inter칠s p칰blico o vayan en beneficio de la salud humana, o para el desarrollo de productos o insumos m칠dicos que no podr칤an desarrollarse de otra manera. Los resultados de los estudios e investigaciones cient칤ficas que utilicen datos personales relativos a la salud o al perfil biol칩gico pueden ser publicados o difundidos libremente. Para ello deber치 previamente anonimizarse los datos que se publiquen.

**d)** Cuando el tratamiento de los datos sea necesario para la formulaci칩n, ejercicio o defensa de un derecho ante los tribunales de justicia o ante un 칩rgano administrativo.

**e)** Cuando el tratamiento sea necesario para fines de medicina preventiva o laboral, evaluaci칩n de la capacidad laboral del trabajador, diagn칩stico m칠dico, prestaci칩n de asistencia o tratamiento de tipo sanitario o social, o gesti칩n de sistemas y servicios de asistencia sanitaria y social.

**f)** Cuando la ley as칤 lo permita e indique expresamente la finalidad que deber치 tener dicho tratamiento.

Se proh칤be el tratamiento y la cesi칩n de los datos relativos a la salud y al perfil biol칩gico de un titular y las muestras biol칩gicas asociadas a una persona identificada o identificable, incluido el almacenamiento del material biol칩gico, cuando los datos o muestras han sido recolectados en el 치mbito laboral, educativo, deportivo, social, de seguros, de seguridad o identificaci칩n, salvo que la ley expresamente autorice su tratamiento en casos calificados y que se refiera a alguno de los casos mencionados en este art칤culo.

Las excepciones para tratar datos sin el consentimiento mencionado en este art칤culo se entienden aplicables al tratamiento de datos que no revisten el car치cter especial a que se refiere este precepto.


**Art칤culo 16췈 ter**.- Datos personales biom칠tricos. Son datos personales biom칠tricos aquellos obtenidos a partir de un tratamiento t칠cnico espec칤fico, relativos a las caracter칤sticas f칤sicas, fisiol칩gicas o conductuales de una persona que permitan o confirmen la identificaci칩n 칰nica de ella, tales como la huella digital, el iris, los rasgos de la mano o faciales y la voz.

S칩lo podr치n tratarse estos datos cuando se cumpliere con lo dispuesto en el inciso primero del art칤culo 16 y siempre que el responsable proporcione al titular la siguiente informaci칩n espec칤fica:

**a)** La identificaci칩n del sistema biom칠trico usado;

**b)** La finalidad espec칤fica para la cual los datos recolectados por el sistema biom칠trico ser치n utilizados;

**c)** El per칤odo durante el cual los datos biom칠tricos ser치n utilizados, y

**d)** La forma en que el titular puede ejercer sus derechos.

Los datos personales biom칠tricos podr치n tratarse sin consentimiento s칩lo en los casos se침alados en el inciso segundo del art칤culo 16 bis.


**Art칤culo 16췈 qu치ter**.- Datos personales relativos a los ni침os, ni침as y adolescentes. El tratamiento de los datos personales que conciernen a los ni침os, ni침as y adolescentes, s칩lo puede realizarse atendiendo al inter칠s superior de 칠stos y al respeto de su autonom칤a progresiva.

Cumpli칠ndose la exigencia establecida en el inciso anterior, para tratar los datos personales de los ni침os y ni침as se requiere el consentimiento otorgado por sus padres o representantes legales o por quien tiene a su cargo el cuidado personal del ni침o o ni침a, salvo que expresamente lo autorice o mandate la ley.

Los datos personales de los adolescentes se podr치n tratar de acuerdo a las normas de autorizaci칩n previstas en esta ley para los adultos, salvo lo dispuesto en el inciso siguiente.

Los datos personales sensibles de los adolescentes menores de 16 a침os s칩lo se podr치n tratar con el consentimiento otorgado por sus padres o representantes legales o quien tiene a su cargo el cuidado personal del menor, salvo que expresamente lo autorice o mandate la ley.

Para los efectos de esta ley, se consideran ni침os o ni침as a los menores de catorce a침os, y adolescentes, a los mayores de catorce y menores de dieciocho a침os.

Constituye una obligaci칩n especial de los establecimientos educacionales y de todas las personas o entidades p칰blicas o privadas que traten o administren datos personales de ni침os, ni침as y adolescentes, incluido quienes ejercen su cuidado personal, velar por el uso l칤cito y la protecci칩n de la informaci칩n personal que concierne a los ni침os, ni침as y adolescentes.



**Art칤culo 16췈 quinquies**.- Datos personales con fines hist칩ricos, estad칤sticos, cient칤ficos y de estudios o investigaciones. Se entiende que existe un inter칠s leg칤timo en el tratamiento de datos personales que realicen las personas naturales o jur칤dicas, p칰blicas o privadas, incluidos los organismos p칰blicos, cuando el tratamiento se realiza exclusivamente con fines hist칩ricos, estad칤sticos, cient칤ficos y para estudios o investigaciones, todos los cuales deben atender fines de inter칠s p칰blico.

Los responsables de datos deber치n adoptar y acreditar que han cumplido con todas las medidas de calidad y seguridad necesarias para resguardar que los datos se utilicen exclusivamente para tales fines. En el caso de los datos personales sensibles, el responsable debe identificar los riesgos posibles e implementar las medidas tendientes a su reducci칩n o mitigaci칩n. Cumplidas estas condiciones, el responsable podr치 almacenar y utilizar los datos por un per칤odo indeterminado de tiempo.

Los responsables que hayan tratado datos personales exclusivamente con estas finalidades podr치n efectuar publicaciones con los resultados y an치lisis obtenidos, debiendo previamente adoptar las medidas necesarias para anonimizar los datos que se publiquen.


**Art칤culo 16췈 sexies**.- Datos de geolocalizaci칩n. El tratamiento de los datos personales de geolocalizaci칩n del titular se podr치 realizar bajo las mismas fuentes de licitud establecidas en los art칤culos 12 y 13.

El titular de datos deber치 ser informado de manera clara, suficiente y oportuna, del tipo de datos de geolocalizaci칩n que ser치n tratados, de la finalidad y duraci칩n del tratamiento y si los datos
