---
title: "游닇 T칤tulo 04"
---

## T칤tulo IV: Del tratamiento de datos personales por los 칩rganos p칰blicos


### Art칤culo 20

**Art칤culo 20췈**.- Regla general del tratamiento de datos por 칩rganos p칰blicos. Es l칤cito el tratamiento de los datos personales que efect칰an los 칩rganos p칰blicos cuando se realiza para el cumplimiento de sus funciones legales dentro del 치mbito de sus competencias, de conformidad a las normas establecidas en la ley y a las disposiciones previstas en este T칤tulo. En esas condiciones, los 칩rganos p칰blicos act칰an como responsables de datos y no requieren el consentimiento del titular para tratar sus datos personales.


### Art칤culo 21

**Art칤culo 21췈**.- Principios y normas aplicables al tratamiento de datos de los 칩rganos p칰blicos. El tratamiento de los datos personales que realicen los 칩rganos p칰blicos se rige por los principios establecidos en el art칤culo 3췈 de esta ley y los principios generales que rigen la Administraci칩n del Estado, especialmente los principios de coordinaci칩n, probidad y eficiencia.

En virtud del principio de coordinaci칩n, los organismos p칰blicos deben alcanzar un alto grado de interoperabilidad y coherencia, de modo de evitar contradicciones en la informaci칩n almacenada y reiteraci칩n de requerimientos de informaci칩n o documentos a los titulares de datos. Conforme al principio de eficiencia, se debe evitar la duplicaci칩n de procedimientos y tr치mites entre los organismos p칰blicos y entre 칠stos y los titulares de la informaci칩n.

Sin perjuicio de las dem치s normas establecidas en el presente T칤tulo, son aplicables al tratamiento de datos que efect칰en los 칩rganos p칰blicos las disposiciones establecidas en los art칤culos 2췈, 14, 14 bis, 14 ter, 14 qu치ter, 14 quinquies, 14 sexies y 15 bis, los art칤culos del P치rrafo Segundo y Tercero del T칤tulo II, los art칤culos del T칤tulo V y los art칤culos del T칤tulo VII de esta ley. Asimismo, le son aplicables los art칤culos 4췈, 5췈, 6췈, 7췈 y 8췈 en conformidad a lo dispuesto en el art칤culo 23.


### Art칤culo 22

**Art칤culo 22췈**.- Comunicaci칩n o cesi칩n de datos por un 칩rgano p칰blico. Los 칩rganos p칰blicos est치n facultados para comunicar o ceder datos personales espec칤ficos, o todo o parte de sus bases de datos o conjuntos de datos, a otros 칩rganos p칰blicos, siempre que la comunicaci칩n o cesi칩n de los datos resulte necesaria para el cumplimiento de sus funciones legales y ambos 칩rganos act칰en dentro del 치mbito de sus competencias. La comunicaci칩n o cesi칩n de los datos se debe realizar para un tratamiento espec칤fico y el 칩rgano p칰blico receptor no los podr치 utilizar para otros fines.

Asimismo, se podr치 comunicar o ceder datos o bases de datos personales entre organismos p칰blicos, exclusivamente cuando ellos se requieran para un tratamiento que tenga por finalidad otorgar beneficios al titular, evitar duplicidad de tr치mites para los ciudadanos o reiteraci칩n de requerimientos de informaci칩n o documentos para los mismos titulares.

El 칩rgano p칰blico receptor de los datos s칩lo puede conservarlos por el tiempo necesario para efectuar el tratamiento espec칤fico para el cual fueron requeridos, luego de lo cual deber치n ser suprimidos o anonimizados. Estos datos se podr치n almacenar por un tiempo mayor cuando el 칩rgano p칰blico requiera atender reclamaciones o impugnaciones, realizar actividades de control o seguimiento, o sirvan para dar garant칤a de las decisiones adoptadas.

Para los efectos de poder comunicar o ceder datos personales a personas o entidades privadas, los organismos p칰blicos deber치n contar con el consentimiento del titular, salvo que la comunicaci칩n o cesi칩n de datos sea necesaria para cumplir las funciones del organismo p칰blico en materia de fiscalizaci칩n o inspecci칩n.

Cuando se trate de comunicar o ceder datos personales en virtud de una solicitud de acceso a la informaci칩n formulada con arreglo a lo establecido en el art칤culo 10 de la ley N춿 20.285, los organismos p칰blicos deber치n contar con el consentimiento del titular obtenido en la oportunidad prevista en el art칤culo 20 de dicha ley.

Respecto de la comunicaci칩n de los datos relativos a infracciones penales, civiles, administrativas y disciplinarias, se aplicar치 lo dispuesto en el art칤culo 25.

Los organismos p칰blicos deber치n informar mensualmente a trav칠s de su p치gina web institucional los convenios suscritos con otros organismos p칰blicos y con entidades privadas relativos a cesi칩n o transferencia de datos personales. Esta obligaci칩n ser치 fiscalizada por la Agencia.


**Art칤culo 23췈**.- Ejercicio de los derechos del titular, procedimiento administrativo de tutela y reclamo de ilegalidad. El titular de datos podr치 ejercer ante el 칩rgano p칰blico los derechos de acceso, rectificaci칩n y oposici칩n que le reconoce esta ley. El titular tambi칠n podr치 oponerse a un tratamiento espec칤fico cuando 칠ste sea contrario a las disposiciones de este T칤tulo. El titular podr치 ejercer el derecho de supresi칩n en los casos previstos en el inciso tercero del art칤culo anterior.

Los organismos p칰blicos no acoger치n las solicitudes de acceso, rectificaci칩n, oposici칩n, supresi칩n o bloqueo temporal de los datos personales en los siguientes casos:

**a)** Cuando con ello se impida o entorpezca el cumplimiento de las funciones fiscalizadoras, investigativas, de protecci칩n a v칤ctimas y testigos, o sancionatorias del organismo p칰blico.

**b)** Cuando con ello se afecte el car치cter secreto de la informaci칩n establecido por la ley.

El ejercicio de los derechos del titular se deber치 realizar de acuerdo al procedimiento establecido en el art칤culo 11 de esta ley, dirigi칠ndose al jefe superior del servicio.

El titular podr치 reclamar ante la Agencia cuando el organismo p칰blico le haya denegado en forma expresa o t치cita una solicitud en que ejerce cualquiera de los derechos que le reconoce esta ley. La reclamaci칩n se sujetar치 a las normas previstas en el procedimiento administrativo de tutela de derechos establecido en el art칤culo 41.


### Art칤culo 24

**Art칤culo 24췈**.- Reg칤menes especiales. El tratamiento, comunicaci칩n o cesi칩n de datos personales sensibles, realizado por 칩rganos p칰blicos competentes en las materias que a continuaci칩n se indican, estar치n sujetos exclusivamente al r칠gimen de regulaci칩n especial establecido en este art칤culo:

**a)** Aqu칠llos que se realicen con fines de prevenci칩n, investigaci칩n, detecci칩n o enjuiciamiento de infracciones penales o de ejecuci칩n de sanciones penales, incluidas las actividades de protecci칩n y prevenci칩n frente a las amenazas y riesgos contra la seguridad p칰blica, protecci칩n a v칤ctimas y testigos, an치lisis criminal y reportabilidad de la informaci칩n criminal. Respecto de los datos que se realicen con esta finalidad, no ser치 aplicable lo dispuesto en el art칤culo 25.

**b)** Aqu칠llos en materias relacionadas directamente con la seguridad de la Naci칩n, la defensa nacional y la pol칤tica exterior del pa칤s.

**c)** Aqu칠llos realizados con el objeto exclusivo de atender una situaci칩n de emergencia o cat치strofe, declarada de conformidad a la ley y s칩lo mientras permanezca vigente esta declaraci칩n.

**d)** Aqu칠llos que se encuentren protegidos por normas de secreto, reserva o confidencialidad, establecidas en sus respectivas leyes. Dentro de esta excepci칩n se entienden tambi칠n comprendidos los datos que, en cumplimiento de una obligaci칩n legal, los 칩rganos p칰blicos deban ceder a otro 칩rgano p칰blico o a terceros, debiendo en tal caso el receptor tratarlos manteniendo la misma obligaci칩n de secreto, reserva o confidencialidad.

Los 칩rganos p칰blicos correspondientes podr치n tratar, ceder y comunicar datos personales de forma l칤cita, siempre y cuando se realice para el cumplimiento de sus funciones legales, dentro del 치mbito de sus competencias y respetando las garant칤as fundamentales establecidas en el art칤culo 19, N춿 4, de la Constituci칩n Pol칤tica de la Rep칰blica y los principios establecidos en el art칤culo 3춿.

Con el objeto de realizar los tratamientos, cesiones y comunicaciones de datos para la finalidad prevista en las letras **a)**, **b)** y **c)** anteriores, los 칩rganos p칰blicos y sus autoridades estar치n obligadas a intercambiar informaci칩n y proporcionar los datos personales que les sean requeridos para estos fines, siempre que se refieran a tratamientos que se realicen con una finalidad espec칤fica autorizada por ley o, cuando esto no sea posible, el requerimiento sea una medida necesaria y proporcional.

La Agencia de Protecci칩n de Datos Personales podr치, oyendo previamente a los 칩rganos competentes, dictar instrucciones para especificar la forma de aplicar las referidas garant칤as y principios a los casos mencionados, de manera de asegurar su resguardo y permitir el debido cumplimiento de las funciones legales de los 칩rganos correspondientes.

### Art칤culo 25

**Art칤culo 25췈**.- Datos relativos a infracciones penales, civiles, administrativas y disciplinarias. Los datos personales relativos a la comisi칩n y sanci칩n de infracciones penales, civiles, administrativas y disciplinarias s칩lo pueden ser tratados por los organismos p칰blicos para el cumplimiento de sus funciones legales, dentro del 치mbito de sus competencias y en los casos expresamente previstos en la ley.

En las comunicaciones que realicen los organismos p칰blicos, con ocasi칩n del tratamiento de estos datos personales, deber치n velar en todo momento porque la informaci칩n comunicada o hecha p칰blica sea exacta, suficiente, actual y completa.

No podr치n comunicarse o hacerse p칰blicos los datos personales relativos a la comisi칩n y condena de infracciones penales, civiles, administrativas o disciplinarias, una vez prescrita la acci칩n penal, civil, administrativa o disciplinaria respectiva, o una vez que se haya cumplido o prescrito la pena o la sanci칩n impuesta, lo que deber치 ser declarado o constatado por la autoridad p칰blica competente. Lo anterior es sin perjuicio de la incorporaci칩n, mantenimiento y consulta de esta informaci칩n en los registros que llevan los 칩rganos p칰blicos por expresa disposici칩n de la ley, en la forma y por el tiempo previsto en la ley que establece la obligaci칩n espec칤fica correspondiente. Las personas que se desempe침en en los 칩rganos p칰blicos est치n obligadas a guardar secreto respecto de esta informaci칩n, la que deber치 ser mantenida como informaci칩n reservada.

Cuando la ley disponga que la informaci칩n relativa a la comisi칩n y sanci칩n de infracciones penales, civiles, administrativas y disciplinarias deba hacerse p칰blica a trav칠s de su incorporaci칩n en un registro de sanciones, o su publicaci칩n en el sitio web de un 칩rgano p칰blico o en cualquier otro medio de comunicaci칩n o difusi칩n, sin fijar un per칤odo de tiempo durante el cual deba permanecer disponible esta informaci칩n, se seguir치n las siguientes reglas:

**a)** Respecto de las infracciones penales, los plazos de publicidad se regir치n por las normas particulares que rigen para este tipo de infracciones.

**b)** Respecto de las infracciones civiles, administrativas y disciplinarias, permanecer치n accesibles al p칰blico por el per칤odo de cinco a침os.

Se proh칤be el tratamiento masivo de los datos personales contenidos en los registros electr칩nicos de infracciones penales, civiles, administrativas y disciplinarias que lleven los organismos p칰blicos. El incumplimiento de esta prohibici칩n constituye una infracci칩n grav칤sima de conformidad a esta ley.

Except칰anse de la prohibici칩n de comunicaci칩n los casos en que la informaci칩n sea solicitada por los tribunales de justicia u otro organismo p칰blico para el cumplimiento de sus funciones legales y dentro del 치mbito de su competencia, quienes deber치n mantener la debida reserva.

No obstante lo dispuesto en el inciso tercero del presente art칤culo, los datos personales relativos a la comisi칩n y sanci칩n de infracciones penales revisten car치cter reservado y, salvo las disposiciones legales que autorizan su tratamiento, no podr치n ser comunicados o cedidos a terceras personas por los organismos p칰blicos que los posean.


### Art칤culo 26

**Art칤culo 26췈**.- Reglamento. Las condiciones, modalidades e instrumentos para la comunicaci칩n o cesi칩n de datos personales entre organismos p칰blicos y con personas u organismos privados, se regular치n a trav칠s de un reglamento expedido por el Ministerio Secretar칤a General de la Presidencia y suscrito por el Ministro de Hacienda y por el Ministro de Econom칤a, Fomento y Turismo, previo informe de la Agencia. En este mismo reglamento se regular치n los procedimientos de anonimizaci칩n de los datos personales, especialmente los datos personales sensibles.

Con todo, este reglamento no ser치 aplicable a aquellas cesiones en las que tenga participaci칩n alguno de los 칩rganos a los que se refiere el T칤tulo VIII de esta ley.
