---
title: "游닇 T칤tulo 05"
---

## T칤tulo V: De la transferencia internacional de datos personales


### Art칤culo 27

**Art칤culo 27췈**.- Regla general de autorizaci칩n Cumpli칠ndose los requisitos que, de conformidad a esta ley, autorizan al tratamiento de datos, son l칤citas las operaciones de transferencia internacional de datos en cualquiera de los siguientes casos:

**a)** Cuando la transferencia se realice a una persona, entidad u organizaci칩n p칰blica o privada sujeta al ordenamiento jur칤dico de un pa칤s que proporcione niveles adecuados de protecci칩n de datos personales, de conformidad a lo dispuesto en el art칤culo 28.

**b)** Cuando la transferencia de datos quede amparada por cl치usulas contractuales, normas corporativas vinculantes u otros instrumentos jur칤dicos suscritos entre el responsable que efect칰a la transferencia y el responsable o tercero mandatario que la reciba, y en ellas se establezcan garant칤as adecuadas de conformidad a lo dispuesto en el art칤culo 28.

**c)** Cuando el responsable que efect칰a la transferencia y el responsable o tercero mandatario que la recibe adopten un modelo de cumplimiento o mecanismo de certificaci칩n, y en ellos se establezcan garant칤as adecuadas de conformidad con el art칤culo 28.

En ausencia de una decisi칩n de adecuaci칩n o de garant칤as adecuadas, se podr치 realizar una transferencia espec칤fica y que no sea habitual si se cumple alguno de los siguientes supuestos:

**a)** Cuando exista consentimiento expreso del titular de datos para realizar una transferencia internacional de datos espec칤fica y determinada.

**b)** Cuando se refiera a transferencias bancarias, financieras o burs치tiles espec칤ficas y que se realicen conforme a las leyes que regulan estas transferencias.

**c)** Cuando se deban transferir datos para dar cumplimiento a obligaciones adquiridas en tratados o convenios internacionales que hayan sido ratificados por el Estado chileno y se encuentren vigentes.

**d)** Cuando la transferencia resulte necesaria por aplicaci칩n de convenios de cooperaci칩n, intercambio de informaci칩n o supervisi칩n que hayan sido suscritos por 칩rganos p칰blicos para el cumplimiento de sus funciones y en el ejercicio de sus competencias.

**e)** Cuando la transferencia de datos realizada por una persona natural o jur칤dica, p칰blica o privada, haya sido autorizada expresamente por la ley y para una finalidad determinada.

**f)** Cuando la transferencia sea efectuada con el objeto de prestar o solicitar colaboraci칩n judicial internacional.

**g)** Cuando la transferencia sea necesaria para la celebraci칩n o ejecuci칩n de un contrato entre el titular y el responsable, o para la ejecuci칩n de medidas precontractuales adoptadas a solicitud del titular.

**h)** Cuando sea necesario adoptar medidas urgentes en materia m칠dica o sanitaria para la prevenci칩n o diagn칩stico de enfermedades, para tratamientos m칠dicos o para la gesti칩n de servicios sanitarios o de salud.

### Art칤culo 28

**Art칤culo 28췈**.- Regla de determinaci칩n de pa칤ses adecuados y dem치s normas aplicables a la transferencia internacional de datos. Se entiende que el ordenamiento jur칤dico de un pa칤s posee niveles adecuados de protecci칩n de datos, cuando cumple con est치ndares similares o superiores a los fijados en esta ley. La Agencia determinar치 fundadamente los pa칤ses que poseen niveles adecuados de protecci칩n de datos considerando, a lo menos, los siguientes:

**a)** El establecimiento de principios que rigen el tratamiento de los datos personales.

**b)** La existencia de normas que reconozcan y garanticen los derechos de los titulares de datos y la existencia de una autoridad p칰blica jurisdiccional o administrativa de control o tutela.

**c)** La imposici칩n de obligaciones de informaci칩n y seguridad a los responsables del tratamiento de los datos y terceros mandatarios.

**d)** La determinaci칩n de responsabilidades en caso de infracciones.

Se considerar치n garant칤as adecuadas aquellos instrumentos, mecanismos o cl치usulas que contengan similares o mayores principios, derechos y garant칤as a aqu칠llas que ofrece la presente ley, y en particular, que otorguen derechos exigibles y acciones legales efectivas a los titulares de los datos. La Agencia podr치 aprobar cl치usulas modelo y otros instrumentos jur칤dicos, s칩lo si contienen dichas garant칤as para el flujo transfronterizo de datos, los cuales estar치n a disposici칩n de los responsables. Las cl치usulas modelo y otros instrumentos jur칤dicos que establezcan garant칤as adecuadas aprobados por la Agencia no requerir치n ninguna otra garant칤a adicional ni autorizaci칩n.

La Agencia pondr치 en su p치gina web a disposici칩n de los interesados un listado de pa칤ses adecuados y modelos tipo de cl치usulas contractuales y otros instrumentos jur칤dicos para la transferencia internacional de datos.

Cuando la transferencia se efect칰e entre sociedades o entidades que pertenezcan a un mismo grupo empresarial, empresas relacionadas o sujetas a un mismo controlador en los t칠rminos previstos en la Ley de Mercado de Valores, siempre que todas ellas operen bajo los mismos est치ndares y pol칤ticas en materia de tratamiento de datos personales, las transferencias podr치n quedar amparadas en normas corporativas vinculantes previamente aprobadas por la Agencia. El responsable que efect칰e la transferencia de datos asumir치 la responsabilidad por cualquier infracci칩n a los est치ndares y pol칤ticas corporativas vinculantes en que incurra alguno de los miembros del grupo empresarial. El responsable s칩lo podr치 exonerarse de esta responsabilidad cuando acredite que la infracci칩n no fue imputable al miembro del grupo empresarial correspondiente.

Cuando no se verifique ninguna de las circunstancias se침aladas en el art칤culo anterior, la Agencia podr치 autorizar, mediante resoluci칩n fundada, la transferencia internacional de datos para un caso particular, siempre que el transmisor y el receptor de los datos otorguen las garant칤as adecuadas en relaci칩n con la protecci칩n de los derechos de las personas que son titulares de estos datos y la seguridad de la informaci칩n transferida, de conformidad con la presente ley.

Corresponder치 al responsable de datos que efectu칩 la transferencia internacional de datos acreditar ante la Agencia que 칠sta se practic칩 de conformidad a las reglas establecidas en esta ley.


### Art칤culo 29

**Art칤culo 29췈**.- Fiscalizaci칩n. La Agencia fiscalizar치 las operaciones de transferencia internacional de datos, pudiendo formular
 recomendaciones, adoptar medidas conservativas y, en casos calificados, suspender temporalmente el env칤o de los datos.
