---
title: "游닇 T칤tulo 06"
---

## T칤tulo VI: Autoridad de Control en materia de Protecci칩n de Datos Personales

### Art칤culo 30

**Art칤culo 30췈**.- Agencia de Protecci칩n de Datos Personales. Cr칠ase la Agencia de Protecci칩n de Datos Personales, corporaci칩n aut칩noma de derecho p칰blico, de car치cter t칠cnico, descentralizado, con personalidad jur칤dica y patrimonio propio, que se relacionar치 con el Presidente de la Rep칰blica a trav칠s del Ministerio de Econom칤a, Fomento y Turismo.

La Agencia tendr치 por objeto velar por la efectiva protecci칩n de los derechos que garantizan la vida privada de las personas y sus datos personales, de conformidad a lo establecido en la presente ley, y fiscalizar el cumplimiento de sus disposiciones.

El domicilio de la Agencia ser치 fijado en el reglamento, sin perjuicio de los domicilios que pueda establecer en otros puntos del pa칤s.

**Art칤culo 30 bis췈**.- Funciones y atribuciones de la Agencia. La Agencia tendr치 las siguientes funciones y atribuciones:

**a)** Dictar instrucciones y normas generales y obligatorias con el objeto de regular las operaciones de tratamiento de datos personales conforme a los principios establecidos en esta ley. Las instrucciones y normas generales que dicte la Agencia deber치n ser emitidas previa consulta p칰blica efectuada a trav칠s de la p치gina web institucional y deber치n estar relacionadas estrictamente con la regulaci칩n de tratamiento de datos personales y que sea necesaria para el fiel cumplimiento de la presente ley, disponi칠ndose los mecanismos necesarios para que los interesados puedan formular observaciones a 칠sta.

**b)** Aplicar e interpretar administrativamente las disposiciones legales y reglamentarias en materia de protecci칩n de los datos personales y las instrucciones y normas generales que dicte la Agencia.

**c)** Fiscalizar el cumplimiento de las disposiciones de esta ley, sus reglamentos y las instrucciones y normas generales que se dicten respecto de los tratamientos de datos personales. Para ello, podr치 requerir a quienes realicen tratamiento de datos personales la entrega de cualquier documento, libro o antecedente y toda la informaci칩n que fuere necesaria para el cumplimiento de su funci칩n fiscalizadora.

**d)** Determinar las infracciones e incumplimientos en que incurran quienes realicen tratamiento de datos personales, en sus operaciones de tratamiento de datos, respecto de los principios y obligaciones establecidos en esta ley, sus reglamentos y las instrucciones y normas generales que emita la Agencia. Para tales efectos, y de manera fundada, podr치 citar a declarar, entre otros, al titular, a los representantes legales, administradores, asesores y dependientes de quien trate datos personales, as칤 como a toda persona que haya tenido participaci칩n o conocimiento respecto de alg칰n hecho que sea relevante para resolver un procedimiento sancionatorio. Asimismo, podr치 tomar las declaraciones respectivas por otros medios que aseguren su fidelidad.

**e)** Ejercer la potestad sancionadora sobre las personas naturales o jur칤dicas que traten datos personales con infracci칩n a esta ley, sus reglamentos y a instrucciones y normas generales dictadas por la Agencia, aplicando las sanciones establecidas en la presente ley.

**f)** Resolver las solicitudes y reclamos que formulen los titulares de datos en contra de quienes traten datos personales con infracci칩n a esta ley, sus reglamentos o las instrucciones y normas generales dictadas por la Agencia.

**g)** Desarrollar programas, proyectos y acciones de difusi칩n, promoci칩n e informaci칩n a la ciudadan칤a, en relaci칩n al respeto a la protecci칩n de sus datos personales.

**h)** Proponer al Presidente de la Rep칰blica y al Congreso Nacional, en su caso, las normas legales y reglamentarias para asegurar a las personas la debida protecci칩n de sus datos personales y perfeccionar la regulaci칩n sobre el tratamiento y uso de esta informaci칩n.

**i)** Prestar asistencia t칠cnica, cuando le sea requerida, al Congreso Nacional, al Poder Judicial, a la Contralor칤a General de la Rep칰blica, al Ministerio P칰blico, al Tribunal Constitucional, al Banco Central, al Servicio Electoral, a la Justicia Electoral y los dem치s tribunales especiales creados por ley, en la dictaci칩n y ejecuci칩n de las pol칤ticas y normas internas de estos organismos, con el objeto que sus operaciones y actividades de tratamiento de datos personales se realicen conforme a los principios y obligaciones establecidos en esta ley.

**j)** Relacionarse y colaborar con los 칩rganos p칰blicos en el dise침o e implementaci칩n de pol칤ticas y acciones destinadas a velar por la protecci칩n de los datos personales y su correcto tratamiento.

**k)** Suscribir convenios de cooperaci칩n y colaboraci칩n con entidades p칰blicas o privadas, nacionales, extranjeras o internacionales, que tengan competencia o est칠n relacionadas al 치mbito de los datos personales. En los casos de suscribir convenios con entidades p칰blicas internacionales se requerir치 consultar previamente al Ministerio de Relaciones Exteriores, de conformidad a lo establecido en el art칤culo 35 de la ley N춿 21.080.

**l)** Participar, recibir cooperaci칩n y colaborar con organismos internacionales en materias de protecci칩n de datos personales.

**m)** Certificar, registrar y supervisar los modelos de prevenci칩n de infracciones y los programas de cumplimiento y administrar el Registro Nacional de Sanciones y Cumplimiento.

**n)** Ejercer las dem치s funciones y atribuciones que la ley le encomiende.

Requerido un organismo de la Administraci칩n para el ejercicio de las funciones o atribuciones que esta ley le entrega a la Agencia, deber치 dar cumplimiento a lo dispuesto en el inciso segundo del art칤culo 14 de la ley N춿 19.880.

**Art칤culo 30 ter췈**.- Direcci칩n de la Agencia. La direcci칩n superior de la Agencia le corresponder치 al Consejo Directivo de la Agencia, el cual tendr치 las siguientes funciones y atribuciones:

**a)** Ejercer las atribuciones y cumplir las funciones que la ley le encomiende a la Agencia.

**b)** Establecer normativa interna de funcionamiento de la Agencia para el cumplimiento de las funciones encomendadas por la ley.

**c)** Establecer pol칤ticas de planificaci칩n, organizaci칩n, direcci칩n, supervisi칩n, coordinaci칩n y control de funcionamiento de la Agencia, as칤 como las de administraci칩n, adquisici칩n y enajenaci칩n de bienes.

**d)** Dictar normas de car치cter general, circulares, oficios circulares y otras resoluciones que se requieran.

**e)** Formular al Presidente de la Rep칰blica o al Congreso Nacional las propuestas de reforma a normas legales y reglamentarias.

**f)** Elaborar, dentro del primer cuatrimestre de cada a침o, una cuenta p칰blica anual en que se detalle el trabajo efectuado por la Agencia en el a침o inmediatamente anterior.


**Art칤culo 30 qu치ter췈**.- Miembros del Consejo Directivo de la Agencia. El Consejo Directivo de la Agencia estar치 integrado por tres consejeros, designados por el Presidente de la Rep칰blica, con acuerdo del Senado, adoptado por los dos tercios de sus miembros en ejercicio.

Para efectos de su designaci칩n, el Presidente de la Rep칰blica har치 la proposici칩n de la n칩mina que corresponda y el Senado deber치 pronunciarse respecto de la propuesta.

Los candidatos a consejero deber치n ser personas de reconocido prestigio profesional o acad칠mico en materias de protecci칩n de datos personales.

El Consejo Directivo de la Agencia designar치 a su presidente y vicepresidente, de entre sus miembros, de conformidad con lo establecido en los estatutos de la Agencia. Los cargos de presidente y vicepresidente durar치n tres a침os o el tiempo que les reste como consejeros en cada caso.

Los consejeros durar치n seis a침os en sus cargos, no podr치n ser designados para un nuevo periodo y se renovar치n de forma individual, cada dos a침os.

El cargo de consejero del Consejo Directivo de la Agencia exige dedicaci칩n exclusiva.

El Consejo Directivo de la Agencia adoptar치 sus decisiones por la mayor칤a de sus miembros y, en caso de empate, resolver치 su presidente, o su vicepresidente en caso de ausencia del presidente. El qu칩rum m칤nimo para sesionar ser치 de dos consejeros. El reglamento establecer치 las dem치s normas necesarias para su funcionamiento.

El Consejo Directivo de la Agencia deber치 celebrar sesiones ordinarias a lo menos una vez por semana, y sesiones extraordinarias cuando las cite especialmente su presidente por s칤 o a requerimiento escrito de dos consejeros, en la forma y condiciones que determine su normativa interna de funcionamiento. El presidente no podr치 negarse a realizar la citaci칩n indicada, debiendo la respectiva sesi칩n tener lugar dentro de los dos d칤as h치biles siguientes al requerimiento se침alado.


**Art칤culo 30 quinquies췈**.- Inhabilidades e incompatibilidades. El cargo de consejero es incompatible con el desempe침o de todo cargo o servicio, sea o no remunerado, que se preste en el sector privado. De igual forma, es incompatible con la calidad de integrante de los 칩rganos de direcci칩n de los partidos pol칤ticos, funcionarios de la Administraci칩n del Estado, y de todo empleo o servicio retribuido con fondos fiscales o municipales, y con las funciones, remuneradas o no, de consejero, director o trabajador de instituciones, organismos aut칩nomos nacionales o extranjeros, empresas del Estado y, en general, de todo servicio p칰blico creado por ley, como asimismo, de empresas, sociedades o entidades p칰blicas o privadas en que el Estado, sus empresas, sociedades o instituciones centralizadas o descentralizadas, tengan aportes de capital mayoritario o en igual proporci칩n o, en las mismas condiciones, representaci칩n o participaci칩n. Asimismo, es incompatible con cualquier otro servicio o empleo remunerado o gratuito en cualquier poder del Estado.

El cargo de consejero es compatible con el desempe침o de cargos docentes en instituciones p칰blicas o privadas reconocidas por el Estado, hasta un m치ximo de doce horas semanales.

El c칩nyuge o conviviente civil de cualquiera de los consejeros y sus parientes hasta el segundo grado de consanguinidad inclusive, no podr치n ser director ni tener participaci칩n en la propiedad de una empresa cuyo objeto o giro comercial verse sobre recolecci칩n, tratamiento o comunicaci칩n de datos personales.

Adicionalmente, no podr치 ser designado consejero:

**a)** La persona que hubiere sido condenada por delito que merezca pena

 aflictiva o inhabilitaci칩n perpetua para desempe침ar cargos u oficios p칰blicos, por delitos de prevaricaci칩n, cohecho y aqu칠llos cometidos en el ejercicio de la funci칩n p칰blica, delitos tributarios y los delitos contra la fe p칰blica.

**b)** La persona que tuviere dependencia de sustancias o drogas estupefacientes o sicotr칩picas ilegales, a menos que justifique su consumo por tratamiento m칠dico.

**c)** La persona que haya sido sancionada, dentro de los 칰ltimos cinco a침os, por infracci칩n grave o grav칤sima a las normas que regulan el tratamiento de los datos personales y su protecci칩n.

**d)** Quienes, dentro del 칰ltimo a침o, hayan sido gerentes, delegados de datos, directores o hayan tenido participaci칩n en la propiedad de una empresa cuyo objeto o giro comercial verse sobre el tratamiento de datos personales.

En todo lo no expresamente regulado en este art칤culo, regir치n las normas del P치rrafo 2춿 del T칤tulo III del decreto con fuerza de ley N춿 1-19.653, de 2000, del Ministerio Secretar칤a General de la Presidencia, que fija el texto refundido, coordinado y sistematizado de la ley N춿 18.575, Org치nica Constitucional de Bases Generales de la Administraci칩n del Estado.


**Art칤culo 30 sexies췈**.- Remoci칩n de consejeros y causales de cesaci칩n. Los consejeros ser치n removidos por la Corte Suprema, a requerimiento del Presidente de la Rep칰blica o de la C치mara de Diputados mediante acuerdo adoptado por simple mayor칤a, o a petici칩n de quince diputados, por incapacidad, mal comportamiento o negligencia manifiesta en el ejercicio de sus funciones. La Corte Suprema conocer치 del asunto en pleno especialmente convocado al efecto y para acordar la remoci칩n deber치 reunir el voto conforme de la mayor칤a de sus miembros en ejercicio.

Adem치s de la remoci칩n, ser치n causales de cesaci칩n en el cargo de consejero, las siguientes:

**a)** Expiraci칩n del plazo por el que fue designado.

**b)** Renuncia ante el Presidente de la Rep칰blica.

**c)** Postulaci칩n a un cargo de elecci칩n popular.

**d)** Inhabilidad o incompatibilidad sobreviniente, circunstancia que ser치 calificada por la mayor칤a de los consejeros con exclusi칩n del afectado.

En caso de que uno o m치s consejeros cesare por cualquier causa, proceder치 la designaci칩n de un nuevo consejero, mediante una proposici칩n del Presidente de la Rep칰blica, sujeto al mismo procedimiento dispuesto en el art칤culo 30 qu치ter, por el per칤odo que restare.

Si el consejero que cesare en el cargo en virtud del presente art칤culo invistiere la condici칩n de presidente o vicepresidente del Consejo Directivo de la Agencia, su reemplazante ser치 designado en la forma prevista en el art칤culo 30 qu치ter, por el tiempo que faltare al que produjo la vacante.


**Art칤culo 30 septies췈**.- Remuneraci칩n. El presidente del Consejo Directivo de la Agencia percibir치 una remuneraci칩n bruta mensualizada equivalente a la de un Subsecretario de Estado, y le corresponder치 ejercer las funciones se침aladas en el art칤culo 30 nonies y en las dem치s disposiciones legales pertinentes.

Los dem치s consejeros percibir치n una remuneraci칩n equivalente al 85% de la remuneraci칩n que corresponda al presidente del Consejo Directivo de la Agencia.


**Art칤culo 30 octies췈**.- Estatutos de la Agencia. Los estatutos de la Agencia establecer치n sus normas de funcionamiento. Los estatutos y sus modificaciones ser치n propuestos por la Agencia al Presidente de la Rep칰blica y su aprobaci칩n se dispondr치 mediante decreto supremo expedido a trav칠s del Ministerio de Econom칤a, Fomento y Turismo.


**Art칤culo 30 nonies췈**.- Funciones y atribuciones del presidente del Consejo Directivo de la Agencia. El presidente del Consejo Directivo de la Agencia ser치 el jefe de servicio de la Agencia y tendr치 la representaci칩n judicial y extrajudicial de 칠sta. Tendr치 a su cargo la organizaci칩n y administraci칩n de la Agencia, y le corresponder치 ejercer la vigilancia y control jer치rquico de la actuaci칩n del personal de la Agencia.

Al presidente del Consejo Directivo de la Agencia le corresponder치n especialmente las siguientes funciones y atribuciones:

**a)** Ejercer el rol de jefe de servicio.

**b)** Ejecutar y dar cumplimiento a las normas y acuerdos adoptados por el Consejo Directivo de la Agencia.

**c)** Citar y presidir las sesiones del Consejo Directivo de la Agencia, as칤 como establecer la tabla de materias a ser tratadas en cada sesi칩n.

**d)** Representar legal, judicial y extrajudicialmente a la Agencia.

**e)** Dictar los reglamentos internos necesarios para el buen funcionamiento del Consejo Directivo de la Agencia, previo acuerdo del Consejo Directivo de la Agencia, velando por el cumplimiento de las normas aplicables a la Agencia.

**f)** Contratar al personal de la Agencia y poner t칠rmino a sus servicios, de conformidad a la ley.

**g)** Ejecutar los actos y celebrar las convenciones necesarias para el cumplimiento de los fines del Consejo Directivo de la Agencia.

**h)** Delegar atribuciones o facultades espec칤ficas en funcionarios de la Agencia.

**i)** Conducir las relaciones de la Agencia con los organismos p칰blicos y dem치s 칩rganos del Estado y con las personas o entidades sujetas a la fiscalizaci칩n de 칠sta, como tambi칠n con las entidades reguladoras internacionales de datos personales.

**j)** Ejercer las dem치s funciones que le sean delegadas por el Consejo Directivo de la Agencia.

El vicepresidente del Consejo Directivo de la Agencia asumir치 las funciones y atribuciones del presidente del Consejo Directivo de la Agencia en caso de ausencia de 칠ste.

### Art칤culo 31

**Art칤culo 31췈**.- Coordinaci칩n regulatoria con el Consejo para la Transparencia. Cuando la Agencia deba dictar una instrucci칩n o norma de car치cter general y obligatoria que pueda tener efectos en los 치mbitos de competencia del Consejo para la Transparencia, de acuerdo a las funciones y atribuciones se침aladas en la ley N춿 20.285, le remitir치 todos los antecedentes y requerir치 de 칠ste un informe para efectos de evitar o precaver potenciales conflictos de normas y asegurar la coordinaci칩n, cooperaci칩n y colaboraci칩n entre ambos 칩rganos.

El Consejo para la Transparencia deber치 evacuar el informe solicitado dentro del plazo de treinta d칤as corridos, contado desde la fecha en que hubiere recibido el requerimiento a que se refiere el inciso precedente.

La Agencia considerar치 el contenido de la opini칩n del Consejo para la Transparencia expres치ndolo en la motivaci칩n de la instrucci칩n o norma que dicte. Transcurrido el plazo sin que se hubiere recibido el informe, se proceder치 conforme al inciso segundo del art칤culo 38 de la ley N춿 19.880.

A su vez, cuando el Consejo para la Transparencia deba dictar una instrucci칩n general que tenga claros efectos en los 치mbitos de competencia de la Agencia, de acuerdo a las funciones y atribuciones se침aladas en esta ley, el Consejo para la Transparencia remitir치 los antecedentes y requerir치 informe a la Agencia, la cual deber치 evacuarlo en el plazo de treinta d칤as corridos, contado desde la fecha en que hubiere recibido el requerimiento. El Consejo para la Transparencia considerar치 el contenido de la opini칩n de la Agencia expres치ndolo en la motivaci칩n de la instrucci칩n general que dicte al efecto. Transcurrido el plazo sin que se hubiere recibido el informe, se proceder치 conforme al inciso segundo del art칤culo 38 de la ley N춿 19.880.

### Art칤culo 32

**Art칤culo 32췈**.- Personal de la Agencia y fiscalizaci칩n. Las personas que presten servicios a la Agencia se regir치n por el C칩digo del Trabajo.

Sin perjuicio de lo anterior, ser치n aplicables a este personal las normas de probidad establecidas en la ley N춿 20.880, sobre probidad en la funci칩n p칰blica y prevenci칩n de los conflictos de intereses, y en el T칤tulo III del decreto con fuerza de ley N춿 1-19.653, de 2000, del Ministerio Secretar칤a General de la Presidencia, que fija el texto refundido, coordinado y sistematizado de la ley N춿 18.575, Org치nica Constitucional de Bases Generales de la Administraci칩n del Estado, debiendo dejarse constancia en los contratos respectivos de una cl치usula que as칤 lo disponga.

Las personas que desempe침en funciones directivas en la Agencia ser치n seleccionadas mediante concurso p칰blico efectuado por la Direcci칩n Nacional del Servicio Civil, sobre la base de una terna conformada por el Consejo de Alta Direcci칩n P칰blica para cada caso, de acuerdo con las normas que regulan los procesos de selecci칩n de la Alta Direcci칩n P칰blica seg칰n la ley N춿 19.882.

En caso de que terceros ejerzan, en contra de los consejeros o del personal de la Agencia, acciones judiciales por actos formales o por acciones u omisiones producidas en el ejercicio de sus cargos, la Agencia deber치 proporcionarles defensa jur칤dica. Esta defensa se extender치 a todas aquellas acciones que se inicien en su contra incluso despu칠s de haber cesado en el cargo.

No proceder치 la defensa a que se refiere el inciso anterior en los casos en que los actos formales, acciones u omisiones en cuesti칩n hayan configurado una causal de cesaci칩n imputable a la conducta del respectivo funcionario.

La Agencia deber치 cumplir con las normas establecidas en el decreto ley N췈 1.263, de 1975, sobre Administraci칩n Financiera del Estado.

Asimismo, la Agencia estar치 sometida a la fiscalizaci칩n de la Contralor칤a General de la Rep칰blica, en lo que concierne a su personal y al examen y juzgamiento de sus cuentas.

Las resoluciones de la Agencia estar치n exentas del tr치mite de toma de raz칩n por la Contralor칤a General de la Rep칰blica.


**Art칤culo 32 bis췈**.- Del patrimonio. El patrimonio de la Agencia estar치 formado por:

**a)** El aporte que se contemple anualmente en la Ley de Presupuestos del Sector P칰blico.

**b)** Los bienes muebles e inmuebles que se le transfieran o que adquieran a cualquier t칤tulo y por los frutos que de ellos se perciban.

**c)** Las donaciones que la Agencia acepte. Las donaciones no requerir치n del tr치mite de insinuaci칩n judicial a que se refiere el art칤culo 1401 del C칩digo Civil.

**d)** Las herencias y legados que la Agencia acepte, lo que deber치 hacer siempre con beneficio de inventario. Dichas asignaciones estar치n exentas de toda clase de impuestos y de todo gravamen o pago que les afecten.

**e)** Los aportes de la cooperaci칩n internacional.
