---
title: "游닇 T칤tulo 07"
---

## T칤tulo VII: De las infracciones y sus sanciones, de los procedimientos y de las responsabilidades

### Art칤culo 33

**Art칤culo 33췈**.- R칠gimen general de responsabilidad. El responsable de datos, sea una persona natural o jur칤dica, de derecho p칰blico o privado, que en sus operaciones de tratamiento de datos personales infrinja los principios se침alados en el art칤culo 3춿 y los derechos y obligaciones establecidos en esta ley, ser치 sancionado de conformidad con las normas del presente T칤tulo.

### Art칤culo 34

**Art칤culo 34췈**.- Infracciones leves, graves y grav칤simas. Las infracciones cometidas por los responsables de datos a los principios se침alados en el art칤culo 3춿 y a los derechos y obligaciones establecidos en esta ley se califican, atendida su gravedad, en leves, graves y grav칤simas.

Las responsabilidades en que incurra una persona natural o jur칤dica por las infracciones establecidas en esta ley, se entienden sin perjuicio de las dem치s responsabilidades legales, civiles o penales, que pudieran corresponderle.

### Art칤culo 34 bis

**Art칤culo 34 bis췈**.- Infracciones leves. Se consideran infracciones leves, las siguientes:

**a)** Incumplir total o parcialmente el deber de informaci칩n y transparencia, establecido en el art칤culo 14 ter.

**b)** Carecer de la individualizaci칩n del domicilio postal, correo electr칩nico o medio electr칩nico equivalente que permita comunicarse con el responsable de datos o su representante legal, actualizado y operativo, a trav칠s del cual los titulares de datos puedan dirigir sus comunicaciones o ejercer sus derechos.

**c)** Omitir la respuesta, responder en forma incompleta o fuera de plazo, las solicitudes formuladas por el titular de datos en conformidad a esta ley.

**d)** Omitir el env칤o a la Agencia de las comunicaciones previstas obligatoriamente en esta ley o sus reglamentos.

**e)** Incumplir las instrucciones generales impartidas por la Agencia en los casos que no est칠 sancionado como infracci칩n grave o grav칤sima.

**f)** Cometer cualquier otra infracci칩n a los derechos y obligaciones establecidas en esta ley, que no sea calificada como una infracci칩n grave o grav칤sima.

### Art칤culo 34 ter

**Art칤culo 34 ter췈**.- Infracciones graves. Se consideran infracciones graves, las siguientes:

**a)** Tratar los datos personales sin contar con el consentimiento del titular de datos o sin un antecedente o fundamento legal que otorgue licitud al tratamiento, o tratarlos con una finalidad distinta de aqu칠lla para la cual fueron recolectados.

**b)** Comunicar o ceder datos personales, sin el consentimiento del titular, en los casos en que dicho consentimiento sea necesario, o comunicar o ceder los datos para un fin distinto del autorizado.

**c)** Efectuar tratamiento de datos personales innecesarios en relaci칩n con los fines del tratamiento vulnerando lo dispuesto en el literal c) del art칤culo 3춿.

**d)** Tratar datos personales inexactos, incompletos o desactualizados en relaci칩n con los fines del tratamiento, salvo que la actualizaci칩n de estos datos corresponda al titular en virtud de la ley o el contrato.

**e)** Impedir u obstaculizar el ejercicio leg칤timo de los derechos de acceso, rectificaci칩n, supresi칩n, oposici칩n o portabilidad del titular.

**f)** Omitir la respuesta, responder tard칤amente o denegar la petici칩n sin causa justificada, en los casos de solicitudes fundadas de bloqueo temporal del tratamiento de datos personales de un titular.

**g)** Realizar tratamiento de datos personales de ni침os, ni침as y adolescentes con infracci칩n a las normas previstas en esta ley.

**h)** Realizar tratamiento de datos personales sin cumplir los requisitos establecidos para las personas jur칤dicas de derecho privado sin fines de lucro y cuya finalidad sea pol칤tica, filos칩fica, religiosa, cultural, sindical o gremial, respecto de los datos de sus asociados.

**i)** Vulnerar el deber de secreto o confidencialidad establecido en el art칤culo 14 bis.

**j)** Vulnerar o infringir las obligaciones de seguridad en el tratamiento de los datos personales establecidas en el art칤culo 14 quinquies.

**k)** Omitir las comunicaciones o los registros en los casos de vulneraci칩n de las medidas de seguridad establecidas en el art칤culo 14 quinquies.

**l)** Adoptar medidas de calidad y seguridad insuficientes o no id칩neas para el tratamiento de datos personales con fines hist칩ricos, estad칤sticos o cient칤ficos y para estudios o investigaciones que atiendan fines de inter칠s p칰blico.

**m)** Realizar operaciones de transferencia internacional de datos en contravenci칩n a las normas previstas en esta ley.

**n)** Incumplir una resoluci칩n o un requerimiento espec칤fico y directo que haya impartido la Agencia.

### Art칤culo 34 qu치ter

**Art칤culo 34 qu치ter췈**.- Infracciones grav칤simas. Se consideran infracciones grav칤simas, las siguientes:

**a)** Efectuar tratamiento de datos personales en forma fraudulenta.

**b)** Destinar maliciosamente los datos personales a una finalidad distinta de la consentida por el titular o prevista en la ley que autoriza su tratamiento.

**c)** Comunicar o ceder, a sabiendas, informaci칩n no veraz, incompleta, inexacta o desactualizada sobre el titular de datos.

**d)** Vulnerar el deber de secreto o confidencialidad sobre los datos personales sensibles y datos personales relativos a la comisi칩n y sanci칩n de infracciones penales, civiles, administrativas y disciplinarias.

**e)** Tratar, comunicar o ceder, a sabiendas, datos personales sensibles o datos personales de ni침os, ni침as y adolescentes, en contravenci칩n a las normas de esta ley.

**f)** Omitir en forma deliberada la comunicaci칩n de las vulneraciones a las medidas de seguridad que puedan afectar la confidencialidad, disponibilidad o integridad de los datos personales.

**g)** Efectuar tratamiento masivo de datos personales contenidos en registros electr칩nicos de infracciones penales, civiles, administrativas y disciplinarias, que llevan los organismos p칰blicos, sin contar con autorizaci칩n legal para ello.

**h)** Realizar a sabiendas operaciones de transferencia internacional de datos en contravenci칩n a las normas previstas en esta ley.

**i)** Incumplir una resoluci칩n de la Agencia que resuelve la reclamaci칩n de un titular sobre el ejercicio de sus derechos de acceso, rectificaci칩n, supresi칩n, oposici칩n, portabilidad o bloqueo temporal.

**j)** Entregar, a sabiendas, informaci칩n falsa, incompleta o manifiestamente err칩nea en el proceso de registro o certificaci칩n del modelo de prevenci칩n de infracciones.

**k)** Incumplir la obligaci칩n establecida en el art칤culo 15 ter, en los casos que corresponda.

### Art칤culo 35

**Art칤culo 35췈**.- Sanciones. Las sanciones a las infracciones en que incurran los responsables de datos ser치n las siguientes:

**a)** Las infracciones leves ser치n sancionadas con amonestaci칩n escrita o multa de hasta 5.000 unidades tributarias mensuales.

**b)** Las infracciones graves ser치n sancionadas con multa de hasta 10.000 unidades tributarias mensuales.

**c)** Las infracciones grav칤simas ser치n sancionadas con multa de hasta 20.000 unidades tributarias mensuales.

En cada caso, la Agencia se침alar치 las medidas tendientes a subsanar las causales que dieron motivo a la sanci칩n, las que deber치n ser adoptadas en un plazo no mayor a sesenta d칤as, de lo contrario se impondr치 un recargo de 50% a la multa cursada, sin perjuicio de lo establecido en el art칤culo 49.

En caso de que exista reincidencia, de conformidad al literal a) del inciso segundo del art칤culo 36, la Agencia podr치 aplicar una multa de hasta tres veces el monto asignado a la infracci칩n cometida.

En caso de que el infractor corresponda a una empresa distinta de aqu칠llas definidas como empresas de menor tama침o en el art칤culo segundo de la ley N춿 20.416, que reincida en infracci칩n de car치cter grave o grav칤sima en los t칠rminos de la letra a) del inciso segundo del art칤culo 36, la multa podr치 alcanzar a la m치s gravosa entre la se침alada en el inciso anterior o hasta el monto correspondiente al 2% o 4% de los ingresos anuales por ventas y servicios y otras actividades del giro en el 칰ltimo a침o calendario, seg칰n se trate de infracciones graves o grav칤simas, respectivamente.

### Art칤culo 36

**Art칤culo 36췈**.- Circunstancias atenuantes y agravantes de responsabilidad. Se considerar치n circunstancias atenuantes:

**1.** Las acciones unilaterales de reparaci칩n que realice el responsable y los acuerdos reparatorios convenidos con los titulares de datos que fueron afectados.

**2.** La colaboraci칩n que el infractor preste en la investigaci칩n administrativa practicada por la Agencia.

**3.** La ausencia de sanciones previas del responsable de datos.

**4.** La autodenuncia ante la Agencia. Junto con la autodenuncia, el infractor deber치 comunicar las medidas adoptadas para el cese de los hechos que originaron la infracci칩n o las medidas de mitigaci칩n implementadas, seg칰n corresponda.

**5.** El haber cumplido diligentemente sus deberes de direcci칩n y supervisi칩n para la protecci칩n de los datos personales sujetos a tratamiento, lo que se verificar치 con el certificado expedido de acuerdo a lo dispuesto en el art칤culo 51.

Se considerar치n circunstancias agravantes:

**a)** La reincidencia. Existe reincidencia cuando el responsable ha sido sancionado en dos o m치s ocasiones, en los 칰ltimos treinta meses, por infracci칩n a esta ley. Las resoluciones que aplican las sanciones respectivas deber치n encontrarse firmes o ejecutoriadas.

**b)** El car치cter continuado de la infracci칩n.

**c)** El haber puesto en riesgo la seguridad de los derechos y libertades de los titulares en relaci칩n a sus datos personales.

### Art칤culo 37

**Art칤culo 37췈**.- Determinaci칩n del monto de las multas. Para la determinaci칩n del monto de las multas se침aladas en esta ley, la Agencia deber치 aplicar prudencialmente los siguientes criterios:

**1.** La gravedad de la conducta.

**2.** Si la conducta fue realizada con falta de diligencia o cuidado en aquellos casos que no se consideran estos elementos en la configuraci칩n de la infracci칩n.

**3.** El perjuicio producido con motivo de la infracci칩n, especialmente el n칰mero de titulares de datos que se vieron afectados.

**4.** El beneficio econ칩mico obtenido con motivo de la infracci칩n, en caso de que lo hubiese.

**5.** Si el tratamiento realizado incluye datos personales sensibles o datos personales de ni침os, ni침as y adolescentes.

**6.** La capacidad econ칩mica del infractor.

**7.** Las sanciones aplicadas con anterioridad por la Agencia en las mismas circunstancias.

**8.** Las circunstancias atenuantes y agravantes que concurran.

En caso de que una conducta d칠 origen a dos o m치s infracciones, o cuando una infracci칩n sea medio para cometer otra, se impondr치 una sola multa, considerando siempre la sanci칩n de la infracci칩n m치s grave. En caso de que se verifiquen dos o m치s conductas infraccionales, independientes entre s칤, se acumular치n las sanciones correspondientes a cada una de ellas.

Las multas deber치n ser pagadas en la Tesorer칤a General de la Rep칰blica, a trav칠s de los medios presenciales o digitales que ella disponga, dentro del plazo de diez d칤as h치biles contado desde que la resoluci칩n de la Agencia se encuentre firme. El comprobante de pago correspondiente deber치 ser presentado a la Agencia dentro del plazo de diez d칤as h치biles contado desde que se hubiere efectuado el pago.

Cuando por unos mismos hechos y fundamentos jur칤dicos, el infractor pudiese ser sancionado con arreglo a esta ley y a otra u otras leyes, de las sanciones posibles, se le impondr치 la de mayor gravedad.

### Art칤culo 38

**Art칤culo 38췈**.- Sanciones accesorias. En caso de que se impongan multas por infracciones grav칤simas reiteradas, en un per칤odo de veinticuatro meses, la Agencia podr치 disponer la suspensi칩n de las operaciones y actividades de tratamiento de datos que realiza el responsable de datos, hasta por un t칠rmino de treinta d칤as. Esta suspensi칩n no afectar치 el almacenamiento de datos por parte del responsable.

La suspensi칩n que disponga la Agencia como sanci칩n accesoria podr치 ser parcial o total, y no podr치 decretarse cuando con ello se afecten los derechos de los titulares.

Durante este per칤odo, el responsable deber치 adoptar las medidas necesarias con el objeto de adecuar sus operaciones y actividades a las exigencias dispuestas en la resoluci칩n que orden칩 la suspensi칩n.

Si el responsable no da cumplimiento a lo dispuesto en la resoluci칩n de suspensi칩n temporal, esta medida se podr치 prorrogar indefinidamente, por per칤odos sucesivos de m치ximo treinta d칤as, hasta que el responsable cumpla con lo ordenado.

Cuando la suspensi칩n afecte a una entidad sujeta a supervisi칩n por parte de un organismo p칰blico de car치cter fiscalizador, la Agencia deber치 previamente poner los antecedentes en conocimiento de la autoridad regulatoria correspondiente, para los efectos de cautelar los derechos de los usuarios de dicha entidad.

### Art칤culo 39

**Art칤culo 39췈**.- Registro Nacional de Sanciones y Cumplimiento. Cr칠ase el Registro Nacional de Sanciones y Cumplimiento, administrado por la Agencia. El registro ser치 p칰blico y su acceso gratuito. Se consultar치 y llevar치 en forma electr칩nica.

En 칠l se deber치n consignar a los responsables de datos que hayan sido sancionados por infringir los derechos y obligaciones establecidos en esta ley. Deber치 distinguirse seg칰n la gravedad de la infracci칩n. Adicionalmente, se deber치 consignar la conducta infraccionada, las circunstancias atenuantes y agravantes de responsabilidad, y la sanci칩n impuesta. Tambi칠n se deber치n consignar los responsables que adopten modelos certificados de prevenci칩n de infracciones, con car치cter vigente.

Las anotaciones en el registro ser치n de acceso p칰blico por el per칤odo de cinco a침os, a contar de la fecha en que se practic칩 la anotaci칩n.

### Art칤culo 40

**Art칤culo 40췈**.- Prescripci칩n. Las acciones para perseguir la responsabilidad por las infracciones previstas en esta ley prescriben en el plazo de cuatro a침os, contado desde la ocurrencia del hecho que origin칩 la infracci칩n.

En caso de infracciones continuadas, el plazo de prescripci칩n de las referidas acciones se contar치 desde el d칤a en que la infracci칩n haya cesado.

Se interrumpe la prescripci칩n con la notificaci칩n del inicio del procedimiento administrativo correspondiente.

Las sanciones que se impongan por una infracci칩n a la presente ley prescriben en el plazo de tres a침os, contado desde la fecha en que la resoluci칩n que impone la sanci칩n quede ejecutoriada.

### Art칤culo 41

**Art칤culo 41췈**.- Procedimiento administrativo de tutela de derechos. El titular de datos podr치 reclamar ante la Agencia cuando el responsable le haya denegado una solicitud realizada de conformidad al art칤culo 11 de la presente ley, o no hubiere dado respuesta a dicha solicitud dentro del plazo legal establecido en ese art칤culo.

La reclamaci칩n presentada se tramitar치 conforme a las siguientes reglas:

**a)** Deber치 ser presentada por escrito, en formato f칤sico o electr칩nico, dentro del plazo de treinta d칤as h치biles contado desde que reciba la respuesta negativa del responsable de datos o haya vencido el plazo que dispon칤a el responsable para responder el requerimiento formulado por el titular. La reclamaci칩n deber치 se침alar la decisi칩n impugnada en caso de rechazo u omisi칩n de respuesta y acompa침ar todos los antecedentes en que aqu칠lla se funda e indicar un domicilio postal, una direcci칩n de correo electr칩nico u otro medio electr칩nico equivalente donde se practicar치n las notificaciones.

**b)** Junto con la interposici칩n del reclamo, a petici칩n fundada del titular y solo en casos justificados, la Agencia podr치 suspender el tratamiento de los datos personales que conciernen al titular y que son objeto de la reclamaci칩n, debiendo previamente o칤r al responsable de datos.

**c)** Recibido el reclamo, la Agencia, dentro de los diez d칤as h치biles siguientes, deber치 determinar si 칠ste cumple con los requisitos establecidos en la letra a) para ser acogido a tramitaci칩n. En caso de que no se acoja a tr치mite la reclamaci칩n, la resoluci칩n de la Agencia debe ser fundada y se notificar치 al titular. En todo caso, se entender치 acogido a tramitaci칩n el reclamo si la Agencia no se pronuncia en el t칠rmino indicado precedentemente.

**d)** Acogido el reclamo a tramitaci칩n, la Agencia notificar치 al responsable de datos, quien dispondr치 de un plazo de treinta d칤as corridos, prorrogables hasta por el mismo plazo, para responder la reclamaci칩n, acompa침ando todos los antecedentes que estime pertinentes. Las notificaciones que se practiquen al responsable se realizar치n a su domicilio postal, direcci칩n de correo electr칩nico u otro medio electr칩nico equivalente a que alude la letra c) del art칤culo 14 ter.

**e)** Vencido este plazo, haya o no contestado el responsable de los datos y, solo si existen hechos sustanciales, pertinentes y controvertidos, la Agencia podr치 abrir un t칠rmino probatorio de diez d칤as h치biles en el cual las partes pueden hacer valer todos los medios de prueba que estimen convenientes.

**f)** El responsable de datos en su respuesta podr치 allanarse a la reclamaci칩n, en cuyo caso deber치 acompa침ar los antecedentes o testimonios que acrediten esta circunstancia. Verificado lo anterior, ser치 notificado el titular de datos, quien tendr치 diez d칤as para hacer valer sus derechos. Cumplido el plazo, la Agencia proceder치 al archivo de los antecedentes, previa aplicaci칩n de la sanci칩n o instrucci칩n al responsable de datos, cuando corresponda.

**g)** La Agencia tendr치 amplias facultades para solicitar antecedentes o informes que contribuyan a su resoluci칩n. Podr치 convocar a las partes a una audiencia e instarlas a alcanzar un acuerdo. Las opiniones que puedan expresar los funcionarios de la Agencia en esta audiencia no los inhabilitar치n para seguir conociendo del asunto en caso de que no se alcance un acuerdo. Logrado el acuerdo se archivar치n los antecedentes.

**h)** La resoluci칩n del reclamo deber치 dictarse por la Agencia y deber치 ser fundada. El procedimiento administrativo de tutela de derechos no podr치 superar los seis meses.

**i)** La resoluci칩n de la Agencia que no acoge a tramitaci칩n un reclamo y la resoluci칩n que resuelve la reclamaci칩n, podr치n ser impugnadas judicialmente dentro del plazo de quince d칤as h치biles contado desde su notificaci칩n, a trav칠s del procedimiento establecido en el art칤culo 43.

Las reclamaciones y las solicitudes de suspensi칩n del tratamiento formuladas en caso de rechazo de una solicitud de bloqueo temporal deber치n ser resueltas por la Agencia en el plazo m치ximo de tres d칤as h치biles, sin necesidad de o칤r previamente a las partes.

### Art칤culo 42

**Art칤culo 42췈**.- Procedimiento administrativo por infracci칩n de ley. La determinaci칩n de las infracciones que cometan los responsables de datos por incumplimiento o vulneraci칩n de los principios establecidos en el art칤culo 3춿, de los derechos y obligaciones establecidas en esta ley, y la aplicaci칩n de las sanciones correspondientes, se sujetar치 a las siguientes reglas especiales:

**a)** El procedimiento sancionatorio ser치 instruido por la Agencia.

**b)** La Agencia podr치 iniciar un procedimiento sancionatorio, de oficio o a petici칩n de parte, como resultado de un proceso de fiscalizaci칩n o a consecuencia de una reclamaci칩n presentada por un titular de datos, en virtud del procedimiento establecido en los art칤culos 23 y 41 de esta ley. En este 칰ltimo caso, se deber치 certificar la recepci칩n del reclamo. Junto con la apertura del expediente, la Agencia deber치 designar un funcionario responsable de la instrucci칩n del procedimiento.

**c)** La Agencia deber치 presentar una formulaci칩n de cargos en contra del responsable de datos en que describa los hechos que configuran la infracci칩n, los principios y obligaciones incumplidos o vulnerados por el responsable, las normas legales infringidas y cualquier otro antecedente que sirva para sustentar la formulaci칩n.

**d)** La formulaci칩n de cargos debe notificarse al responsable de datos a su domicilio postal, direcci칩n de correo electr칩nico u otro medio electr칩nico equivalente se침alado en la letra c) del art칤culo 14 ter.

**e)** El responsable de datos tendr치 un plazo de quince d칤as h치biles para presentar sus descargos. En esa oportunidad, el responsable de datos puede acompa침ar todos los antecedentes que estime pertinentes para desacreditar los hechos imputados. Junto con los descargos, el responsable deber치 fijar una direcci칩n de correo electr칩nico a trav칠s de la cual se realizar치n todas las dem치s comunicaciones y notificaciones.

**f)** Recibidos los descargos o transcurrido el plazo otorgado para ello, la Agencia podr치 abrir un t칠rmino probatorio de diez d칤as en el caso que existan hechos sustanciales, pertinentes y controvertidos.

**g)** La Agencia dar치 lugar a las medidas o diligencias probatorias que solicite el responsable en sus descargos, siempre que sean pertinentes y necesarias. En caso de rechazo, deber치 fundar su resoluci칩n.

**h)** Los hechos investigados y las responsabilidades de los presuntos infractores pueden acreditarse mediante cualquier medio de prueba admisible en derecho, los que se apreciar치n de acuerdo a las reglas de la sana cr칤tica.

**i)** La Agencia tendr치 amplias facultades para solicitar antecedentes o informes que contribuyan a su resoluci칩n.

**j)** La resoluci칩n que ponga fin al procedimiento sancionatorio debe ser fundada y resolver todas las cuestiones planteadas en el expediente, pronunci치ndose sobre cada una de las alegaciones y defensas formuladas por el responsable de datos, y contendr치 la declaraci칩n de haberse configurado el incumplimiento o vulneraci칩n de los principios, derechos y obligaciones establecidos en la ley por el responsable o su absoluci칩n, seg칰n corresponda. En caso que la Agencia considere que se ha verificado la infracci칩n, en la misma resoluci칩n ponderar치 las circunstancias que agravan o aten칰an la responsabilidad del infractor e impondr치 la sanci칩n, de acuerdo a la gravedad de la infracci칩n cometida.

**k)** La resoluci칩n que establezca el incumplimiento o vulneraci칩n a los principios, derechos y obligaciones de esta ley y aplique la sanci칩n correspondiente deber치 ser fundada. Esta resoluci칩n debe indicar los recursos administrativos y judiciales que procedan contra ella en conformidad a esta ley, los 칩rganos ante los que deben presentarse y los plazos para su interposici칩n. La resoluci칩n de la Agencia que resuelve el procedimiento por infracci칩n de ley ser치 reclamable judicialmente conforme al art칤culo siguiente.

**l)** El procedimiento administrativo de infracci칩n de ley no podr치 superar los seis meses. Cuando hayan transcurrido m치s de seis meses desde la fecha de la certificaci칩n indicada en la letra b) de este art칤culo sin que la Agencia haya resuelto la reclamaci칩n, el interesado podr치 presentar un reclamo de ilegalidad en los t칠rminos previstos en el siguiente art칤culo.

### Art칤culo 43

**Art칤culo 43췈**.- Procedimiento de reclamaci칩n judicial. Las personas naturales o jur칤dicas interesadas que estimen que un acto administrativo que paraliza el procedimiento, o una resoluci칩n final o de t칠rmino emanada de la Agencia, sea ilegal, podr치n deducir un reclamo de ilegalidad ante la Corte de Apelaciones de Santiago o la del lugar donde se encuentre domiciliado el reclamante, a elecci칩n de este 칰ltimo. El reclamo deber치 interponerse dentro de los quince d칤as h치biles siguientes a la notificaci칩n de la resoluci칩n impugnada, seg칰n las siguientes reglas:

**a)** El reclamante se침alar치 en su escrito, con precisi칩n, la resoluci칩n objeto del reclamo, la o las normas legales que se suponen infringidas, la forma en que se ha producido la infracci칩n y, cuando procediere, las razones por las cuales el acto le causa agravio.

**b)** La Corte podr치 declarar inadmisible la reclamaci칩n si el escrito no cumple con las condiciones se침aladas en la letra a) anterior. Asimismo, podr치 decretar orden de no innovar cuando la ejecuci칩n del acto impugnado le produzca un da침o irreparable al recurrente.

**c)** Recibida la reclamaci칩n, la Corte requerir치 de informe de la Agencia, concedi칠ndole un plazo de diez d칤as al efecto.

**d)** Evacuado el traslado o teni칠ndosele por evacuado en rebeld칤a, la Corte puede abrir un t칠rmino de prueba, si as칤 lo estima necesario, el que se regir치 por las reglas de los incidentes que contempla el C칩digo de Procedimiento Civil.

**e)** Vencido el t칠rmino de prueba, se ordenar치 traer los autos en relaci칩n. La vista de esta causa gozar치 de preferencia para su inclusi칩n en la tabla.

**f)** Si la Corte da lugar al reclamo, en su sentencia decidir치 si existi칩 agravio y ordenar치, seg칰n sea procedente, la rectificaci칩n del acto impugnado y la dictaci칩n de la respectiva resoluci칩n, seg칰n corresponda.

**g)** Trat치ndose de reclamaciones en contra de una resoluci칩n que resuelve un procedimiento sancionatorio, la Corte podr치 confirmar o revocar la resoluci칩n impugnada, establecer o desechar la comisi칩n de la infracci칩n, seg칰n corresponda y, mantener, dejar sin efecto o modificar la sanci칩n impuesta al responsable o su absoluci칩n, seg칰n sea el caso.

**h)** En todo aquello no regulado por el presente art칤culo, regir치n las normas establecidas en el C칩digo Org치nico de Tribunales y en el C칩digo de Procedimiento Civil, seg칰n corresponda.

### Art칤culo 44

**Art칤culo 44췈**.- Responsabilidad administrativa del jefe superior del 칩rgano p칰blico. El jefe superior de un 칩rgano p칰blico deber치 velar por que el 칩rgano respectivo realice sus operaciones y actividades de tratamiento de los datos personales con arreglo a los principios, derechos y obligaciones establecidos en el T칤tulo IV de esta ley.

Asimismo, los 칩rganos p칰blicos deber치n someterse a las medidas tendientes a subsanar o prevenir infracciones que indique la Agencia o a los programas de cumplimiento o de prevenci칩n de infracciones del art칤culo 49.

Las infracciones a los principios establecidos en el art칤culo 3춿, y a los derechos y obligaciones en que puedan incurrir los 칩rganos p칰blicos se tipifican en los art칤culos 34 bis, 34 ter y 34 qu치ter, y ser치n sancionadas con multa de veinte por ciento a cincuenta por ciento de la remuneraci칩n mensual del jefe superior del 칩rgano p칰blico infractor. La cuant칤a de la multa se determinar치 considerando la gravedad de la infracci칩n, la naturaleza de los datos tratados y el n칰mero de titulares afectados. En la determinaci칩n de la sanci칩n se deber치n considerar tambi칠n las circunstancias que aten칰an la responsabilidad del infractor.

Si el 칩rgano p칰blico persiste en la infracci칩n, se le aplicar치 al jefe superior del 칩rgano p칰blico el duplo de la sanci칩n originalmente impuesta y la suspensi칩n en el cargo por un lapso de cinco d칤as.

Trat치ndose de datos personales sensibles, la multa ser치 del cincuenta por ciento de la remuneraci칩n mensual del jefe superior del 칩rgano p칰blico y proceder치 la suspensi칩n en el cargo de hasta treinta d칤as.

Las infracciones en que incurra un 칩rgano p칰blico en el tratamiento de los datos personales ser치n determinadas por la Agencia de acuerdo al procedimiento establecido en el art칤culo 42.

Habi칠ndose configurado la infracci칩n, las sanciones administrativas se침aladas en este art칤culo ser치n aplicadas por la Agencia. Con todo, la Contralor칤a General de la Rep칰blica, a petici칩n de la Agencia, podr치, de acuerdo a las normas de su ley org치nica, incoar los procedimientos administrativos y proponer las sanciones que correspondan.

En contra de las resoluciones de la Agencia se podr치 deducir el reclamo de ilegalidad establecido en el art칤culo 43.

Las sanciones previstas en este art칤culo deber치n ser publicadas en el sitio web de la Agencia y del respectivo 칩rgano o servicio dentro del plazo de cinco d칤as h치biles contado desde que la respectiva resoluci칩n quede firme.


### Art칤culo 45

**Art칤culo 45췈**.- Responsabilidad del funcionario infractor. Sin perjuicio de lo dispuesto en el art칤culo anterior, si en el procedimiento administrativo correspondiente se determina que existen responsabilidades individuales de uno o m치s funcionarios del 칩rgano p칰blico, la Contralor칤a General de la Rep칰blica, a petici칩n de la Agencia, iniciar치 una investigaci칩n sumaria para determinar las responsabilidades de dichos funcionarios o lo har치 en el procedimiento administrativo ya iniciado, en su caso. Las sanciones a los funcionarios infractores ser치n determinadas de conformidad a lo dispuesto en el Estatuto Administrativo.

En caso de que el procedimiento administrativo correspondiente determine que cualquiera de los funcionarios involucrados es responsable de alguna de las infracciones grav칤simas se침aladas en el art칤culo 34 qu치ter de esta ley, esta conducta se considerar치 una contravenci칩n grave a la probidad administrativa.


### Art칤culo 46

**Art칤culo 46췈**.- Deber de los funcionarios de reserva y confidencialidad. Los funcionarios de los 칩rganos p칰blicos que traten datos personales y, especialmente, cuando se refieran a datos personales sensibles o datos relativos a la comisi칩n y sanci칩n de infracciones penales, civiles, administrativas y disciplinarias, deben guardar secreto o confidencialidad respecto de la informaci칩n que tomen conocimiento en el ejercicio de sus cargos y abstenerse de usar dicha informaci칩n con una finalidad distinta de la que corresponda a las funciones legales del 칩rgano p칰blico respectivo o utilizarla en beneficio propio o de terceros. Para efectos de lo dispuesto en el inciso segundo del art칤culo 125 del Estatuto Administrativo, se estimar치 que los hechos que configuren infracciones a esta disposici칩n vulneran gravemente el principio de probidad administrativa, sin perjuicio de las dem치s sanciones y responsabilidades que procedan.

Cuando, en cumplimiento de una obligaci칩n legal, un 칩rgano p칰blico comunica o cede a otro 칩rgano p칰blico datos protegidos por normas de secreto o confidencialidad, el organismo p칰blico receptor y sus funcionarios deber치n tratarlos manteniendo la misma obligaci칩n de secreto o confidencialidad.

### Art칤culo 47

**Art칤culo 47췈**.- Norma general. El responsable de datos deber치 indemnizar el da침o patrimonial y extrapatrimonial que cause al o los titulares, cuando en sus operaciones de tratamiento de datos infrinja los principios establecidos en el art칤culo 3춿, los derechos y obligaciones establecidos en esta ley y les cause perjuicio. Lo anterior no obsta al ejercicio de los dem치s derechos que concede esta ley al o los titulares de datos.

La acci칩n indemnizatoria se침alada en el inciso anterior podr치 interponerse una vez ejecutoriada la resoluci칩n que resolvi칩 favorablemente el reclamo interpuesto ante la Agencia o la sentencia se encuentre firme y ejecutoriada, en caso de haber presentado un reclamo de ilegalidad, y se tramitar치 de conformidad a las normas del procedimiento sumario establecidas en los art칤culos 680 y siguientes del C칩digo de Procedimiento Civil.

Las acciones civiles que deriven de una infracci칩n a la presente ley prescribir치n en el plazo de cinco a침os, contado desde que se encuentre ejecutoriada la resoluci칩n administrativa o la sentencia judicial, seg칰n sea el caso, que imponga la multa respectiva.


### Art칤culo 48

**Art칤culo 48췈**.- Prevenci칩n de infracciones. Los responsables de datos, sean personas naturales o jur칤dicas, p칰blicas o privadas, deber치n adoptar acciones destinadas a prevenir la comisi칩n de las infracciones establecidas en los art칤culos 34 bis, 34 ter y 34 qu치ter.

### Art칤culo 49

**Art칤culo 49췈**.- Modelo de prevenci칩n de infracciones. Los responsables de datos podr치n voluntariamente adoptar un modelo de prevenci칩n de infracciones consistente en un programa de cumplimiento.

El programa de cumplimiento deber치 contener, al menos, los siguientes elementos:

**a)** Designaci칩n de un delegado de protecci칩n de datos personales.

**b)** Definici칩n de medios y facultades del delegado de protecci칩n de datos.

**c)** La identificaci칩n del tipo de informaci칩n que la entidad trata, el 치mbito territorial en que opera, la categor칤a, clase o tipos de datos o bases de datos que administra, y la caracterizaci칩n de los titulares de datos.

**d)** La identificaci칩n de las actividades o procesos de la entidad, sean habituales o espor치dicos, en cuyo contexto se genere o incremente el riesgo de comisi칩n de las infracciones se침aladas en los art칤culos 34 bis, 34 ter y 34 qu치ter.

**e)** El establecimiento de protocolos, reglas y procedimientos espec칤ficos que permitan a las personas que intervengan en las actividades o procesos indicados en la letra anterior, programar y ejecutar sus tareas o labores de una manera que prevenga la comisi칩n de las referidas infracciones.

**f)** Mecanismos de reporte interno sobre el cumplimiento de lo dispuesto en la presente ley, y mecanismos de reporte a la Autoridad de Protecci칩n de Datos para el caso del art칤culo 14 sexies.

**g)** La existencia de sanciones administrativas internas, as칤 como de procedimientos de denuncia o castigo de responsabilidades de las personas que incumplan el sistema de prevenci칩n de infracciones.

La regulaci칩n interna a que d칠 lugar la implementaci칩n del programa, en su caso, deber치 ser incorporada expresamente como una obligaci칩n en los contratos de trabajo o de prestaci칩n de servicios de todos los trabajadores, empleados y prestadores de servicios de las entidades que act칰en como responsables de datos o los terceros que efect칰en el tratamiento, incluidos los m치ximos ejecutivos de ellas, o bien, como una obligaci칩n del reglamento interno del que tratan los art칤culos 153 y siguientes del C칩digo del Trabajo. En este 칰ltimo caso, se deben realizar las medidas de publicidad establecidas en el art칤culo 156 del mismo C칩digo.

### Art칤culo 50

**Art칤culo 50췈**.- Atribuciones del delegado. El responsable de datos podr치 designar un delegado de protecci칩n de datos personales.

El delegado de protecci칩n de datos deber치 ser designado por la m치xima autoridad directiva o administrativa del responsable de datos. Se considerar치 como la m치xima autoridad directiva o administrativa al directorio, un socio administrador o a la m치xima autoridad de la empresa o servicio, seg칰n corresponda.

El delegado de protecci칩n de datos deber치 contar con autonom칤a respecto de la administraci칩n, en las materias relacionadas con esta ley. En las micro, peque침as y medianas empresas, el due침o o sus m치ximas autoridades podr치n asumir personalmente las tareas de delegado de protecci칩n de datos.

El delegado de protecci칩n de datos podr치 desempe침ar otras funciones y cometidos, procurando mantener la independencia en su funci칩n. El responsable garantizar치 que dichas funciones y cometidos no den lugar a conflicto de intereses.

Las sociedades o entidades que pertenezcan a un mismo grupo empresarial, empresas relacionadas o sujetas a un mismo controlador en los t칠rminos previstos en la Ley de Mercado de Valores, podr치n designar un 칰nico delegado de protecci칩n de datos, siempre que todas ellas operen bajo los mismos est치ndares y pol칤ticas en materia de tratamiento de datos personales, y el delegado sea accesible para todas las entidades y establecimientos.

La designaci칩n del delegado de protecci칩n de datos debe recaer en una persona que re칰na los requisitos de idoneidad, capacidad y conocimientos espec칤ficos para el ejercicio de sus funciones.

Los titulares de datos podr치n ponerse en contacto con el delegado de protecci칩n de datos en lo que respecta a todas las cuestiones relativas al tratamiento de sus datos personales y al ejercicio de sus derechos al amparo de esta ley.

El delegado de protecci칩n de datos estar치 obligado a mantener estricto secreto o confidencialidad de los datos personales que conociere en ejercicio de su cargo. Los funcionarios p칰blicos que desempe침en estas funciones e infrinjan este deber de secreto o confidencialidad, ser치n sancionados de conformidad a lo que se prescribe en los art칤culos 246 a 247 bis del C칩digo Penal. El responsable se har치 cargo por las infracciones al deber de secreto o confidencialidad que deb칤a cumplir su encargado de prevenci칩n o delegado de protecci칩n, sin perjuicio de las acciones de repetici칩n que pueda ejercer contra 칠ste.

El responsable de datos deber치 disponer que el delegado cuente con los medios y facultades suficientes para el desempe침o de sus funciones, debiendo otorgarle los recursos materiales necesarios para realizar adecuadamente sus labores, en consideraci칩n al tama침o y capacidad econ칩mica de la entidad.

Sin perjuicio de las dem치s funciones que se le puedan asignar, el delegado de protecci칩n de datos tendr치 las siguientes funciones:

**a)** Informar y asesorar al responsable de datos, a los terceros encargados o mandatarios y a los dependientes del responsable, respecto de las disposiciones legales y reglamentarias relativas al derecho a la protecci칩n de los datos personales y a la regulaci칩n de su tratamiento.

**b)** Promover y participar en la pol칤tica que dicte el responsable de datos respecto de la protecci칩n y el tratamiento de los datos personales.

**c)** Supervisar el cumplimiento de la presente ley y de la pol칤tica que dicte el responsable, dentro del 치mbito de su competencia.

**d)** Preocuparse de la formaci칩n permanente de las personas que participan en las operaciones de tratamiento de datos.

**e)** Asistir a los miembros de la organizaci칩n en la identificaci칩n de los riesgos asociados a la actividad de tratamiento y las medidas a adoptar para resguardar los derechos de los titulares de datos personales.

**f)** Desarrollar un plan anual de trabajo y rendir cuenta de sus resultados.

**g)** Absolver las consultas y solicitudes de los titulares de datos.

**h)** Cooperar y actuar como punto de contacto de la Agencia.

### Art칤culo 51

**Art칤culo 51췈**.- Certificaci칩n, registro, supervisi칩n del modelo de prevenci칩n de infracciones y reglamento. La Agencia ser치 la entidad encargada de certificar que el modelo de prevenci칩n de infracciones re칰na los requisitos y elementos establecidos en la ley y su reglamento y supervisarlos.

La Agencia incorporar치 en el Registro Nacional de Sanciones y Cumplimiento a las entidades que posean una certificaci칩n vigente.

Un reglamento expedido a trav칠s del Ministerio de Hacienda y suscrito por el Ministro Secretario General de la Presidencia y por el Ministro de Econom칤a, Fomento y Turismo establecer치 los requisitos, modalidades y procedimientos para la implementaci칩n, certificaci칩n, registro y supervisi칩n de los modelos de prevenci칩n de infracciones.

### Art칤culo 52

**Art칤culo 52췈**.- Vigencia de los certificados. Los certificados expedidos por la Agencia tendr치n una vigencia de tres a침os. Sin perjuicio de lo anterior, quedar치n sin efecto en los siguientes casos:

**a)** Por revocaci칩n efectuada por la Agencia.

**b)** Por fallecimiento del responsable de datos en los casos de personas naturales.

**c)** Por disoluci칩n de la persona jur칤dica.

**d)** Por resoluci칩n judicial ejecutoriada.

**e)** Por cese voluntario de la actividad del responsable de datos.

El t칠rmino de vigencia de un certificado por alguna de las causales se침aladas precedentemente ser치 inoponible a terceros, mientras no sea eliminado del registro.

### Art칤culo 53

**Art칤culo 53췈**.- Revocaci칩n de la certificaci칩n. La Agencia puede revocar la certificaci칩n indicada en los art칤culos precedentes, si el responsable no da cumplimiento a lo establecido en este P치rrafo. Con este objeto, la Agencia podr치 requerir toda aquella informaci칩n que fuere necesaria para el ejercicio de sus funciones.

Los responsables pueden exceptuarse de entregar la informaci칩n solicitada cuando la misma est칠 amparada por una obligaci칩n de secreto o confidencialidad, debiendo acreditar dicha circunstancia.

El incumplimiento en la entrega de la informaci칩n requerida, as칤 como la entrega de informaci칩n falsa, incompleta o manifiestamente err칩nea, ser치 sancionado en conformidad con esta ley.

Cuando un certificado ha sido revocado por la Agencia, para volver a solicitarlo el responsable de datos debe acreditar fehacientemente que la causal que dio origen a su revocaci칩n ha sido subsanada.
