---
title: "游닇 T칤tulo 08"
---

## T칤tulo VIII: Del tratamiento de datos personales por el Congreso Nacional, el Poder Judicial y organismos p칰blicos dotados de autonom칤a constitucional

### Art칤culo 54

**Art칤culo 54췈**.- Regla general del tratamiento de datos personales. Es l칤cito el tratamiento de los datos personales que efect칰an el Congreso Nacional, el Poder Judicial, la Contralor칤a General de la Rep칰blica, el Ministerio P칰blico, el Tribunal Constitucional, el Banco Central, el Servicio Electoral y la Justicia Electoral, y los dem치s tribunales especiales creados por ley, cuando se realiza para el cumplimiento de sus funciones legales, dentro del 치mbito de sus competencias y, de conformidad a las normas especiales que se establecen en sus respectivas leyes org치nicas y a las disposiciones del T칤tulo IV de esta ley aplicables a los 칩rganos p칰blicos, con excepci칩n de lo dispuesto en el art칤culo 14 quinquies y en los art칤culos 44 a 46, en lo referido a la intervenci칩n de la Contralor칤a General de la Rep칰blica en la determinaci칩n de la responsabilidad administrativa y la aplicaci칩n de la ley N춿 18.834. Los funcionarios de estos organismos deber치n guardar secreto de tales datos. En esas condiciones estas instituciones y organismos tienen la calidad de responsables de datos y no requieren el consentimiento del titular para efectuar el tratamiento de sus datos personales.

Las autoridades superiores de los 칩rganos internos de estas instituciones deber치n dictar las pol칤ticas, normas e instrucciones necesarias para dar cumplimiento a los principios y obligaciones establecidos en esta ley, especialmente aqu칠llas que permitan el ejercicio de los derechos que se reconocen a los titulares de datos y las que fijan los est치ndares o condiciones m칤nimas de control, seguridad y resguardo que se deben observar en el tratamiento de los datos personales, pudiendo requerir para ello la asistencia t칠cnica de la Agencia. Asimismo, las autoridades de estos 칩rganos ejercer치n la potestad disciplinaria respecto de sus funcionarios, en relaci칩n a las infracciones que se produzcan en el tratamiento de los datos personales, particularmente las infracciones se침aladas en los art칤culos 34 bis, 34 ter y 34 qu치ter.

### Art칤culo 55

**Art칤culo 55췈**.- Ejercicio de los derechos y reclamaciones. Los titulares de datos ejercer치n los derechos que les reconoce esta ley ante el Congreso Nacional, el Poder Judicial, la Contralor칤a General de la Rep칰blica, el Ministerio P칰blico, el Tribunal Constitucional, el Banco Central, el Servicio Electoral y la Justicia Electoral, y los dem치s tribunales especiales creados por ley, de acuerdo a procedimientos racionales y justos, y ante los organismos que dispongan estas instituciones, de conformidad a lo se침alado en el art칤culo anterior.

En caso que la Contralor칤a General de la Rep칰blica, el Ministerio P칰blico, el Banco Central o el Servicio Electoral denieguen injustificada o arbitrariamente el ejercicio de un derecho reconocido por esta ley a un titular de datos, o bien infrinjan alg칰n principio establecido en el art칤culo 3춿, deber u obligaci칩n establecida en ella, caus치ndole perjuicio, el titular que se vea agraviado o afectado por la decisi칩n del organismo, podr치 reclamar ante la Corte de Apelaciones, de acuerdo al procedimiento dispuesto en el art칤culo 43 de esta ley.

Las autoridades superiores del Congreso Nacional, del Poder Judicial, del Tribunal Constitucional, de la Justicia Electoral y de los dem치s tribunales especiales creados por ley, deber치n asegurarse que en el tratamiento de los datos personales que realizan estas instituciones se cumplen estrictamente con los principios establecidos en el art칤culo 3춿 y los deberes, y se respeten los derechos de los titulares establecidos en esta ley, adoptando las medidas de fiscalizaci칩n y control interno que resulten necesarias y adecuadas para esta finalidad.
